table 'AHP All Data'
	lineageTag: b1bbb663-94ac-468a-94c5-91f69dc9124e

	measure 'Sanctioned Vs Completed' = DIVIDE(SUM('AHP All Data'[Houses Completed]),SUM('AHP All Data'[No. of Dus]),0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a07b7736-708d-49f3-a098-37dc5aa7397c

	measure 'Sanctioned Vs Not Started' = DIVIDE(SUM('AHP All Data'[Not Started]),SUM('AHP All Data'[No. of Dus]),0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5558941a-1711-47de-ae38-b29f0c911060

	measure 'Completed Vs Under Progress' = DIVIDE(SUM('AHP All Data'[Total]),SUM('AHP All Data'[Houses Completed]),0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6438497a-1871-44f2-84fe-a4e491a9872e

	measure 'Allotted Vs Occupied' = DIVIDE(SUM('AHP All Data'[Occupied]),SUM('AHP All Data'[Allotted]),0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 22d57e0b-920d-423d-88b6-3db22eb201f8

	measure 'Completed Measure' = SUM('AHP All Data'[Houses Completed])
		formatString: 0
		lineageTag: b9ff35e5-ddff-4891-aaa1-b5860c11694a

	measure 'Not Started measure' = SUM('AHP All Data'[Not Started])
		formatString: 0
		lineageTag: 268c8a84-c655-439a-8904-6ae9b9b1aab0

	measure 'Allotted Measure' = SUM('AHP All Data'[Allotted])
		formatString: 0
		lineageTag: 7e017fb5-73d3-425f-93c6-a4ff5c97e190

	measure 'Occupied Measure' = SUM('AHP All Data'[Occupied])
		formatString: 0
		lineageTag: ff5a71a6-c7c9-490e-a4cb-491f5a83fb0e

	measure 'Under Progress Measure' = SUM('AHP All Data'[Total])
		formatString: 0
		lineageTag: 70649ef7-f95a-4fc3-ab20-026a1985a1ad

	measure 'No. of Sanctioned Measure' = SUM('AHP All Data'[No. of Dus])
		formatString: 0
		lineageTag: e16ee6f2-b783-42d9-9704-e7f3c70584f2

	measure Measure = "Houses Under" & UNICHAR(10) & "Progress"
		lineageTag: c152a901-e8bf-40f1-b24f-d9f32e9477b4

	column 'S.No.'
		dataType: int64
		formatString: 0
		lineageTag: 9db7b2f6-8f2c-4dfa-b6c2-d43a8eff2162
		summarizeBy: sum
		sourceColumn: S.No.

		annotation SummarizationSetBy = Automatic

	column 'No. of Dus'
		dataType: int64
		formatString: 0
		lineageTag: 4571eaed-924b-4d5e-b4db-8365b01ee9c3
		summarizeBy: sum
		sourceColumn: No. of Dus

		annotation SummarizationSetBy = Automatic

	column 'Houses Completed'
		dataType: int64
		formatString: 0
		lineageTag: 4a59b404-02f3-4c58-a064-c38c0c65a88e
		summarizeBy: sum
		sourceColumn: Houses Completed

		annotation SummarizationSetBy = Automatic

	column 'Plinth Level'
		dataType: int64
		formatString: 0
		lineageTag: bf529a4e-6d9d-41a4-b372-ec57bdfc0d68
		summarizeBy: sum
		sourceColumn: Plinth Level

		annotation SummarizationSetBy = Automatic

	column 'Structure Status'
		dataType: int64
		formatString: 0
		lineageTag: aab9ad81-1ae7-49b9-ad30-fb48f1ccf5f0
		summarizeBy: sum
		sourceColumn: Structure Status

		annotation SummarizationSetBy = Automatic

	column 'Finishing Status'
		dataType: int64
		formatString: 0
		lineageTag: b6cdb477-cc2d-47b4-8ba9-18c52809c795
		summarizeBy: sum
		sourceColumn: Finishing Status

		annotation SummarizationSetBy = Automatic

	column Total
		dataType: int64
		formatString: 0
		lineageTag: c9ba783c-5d63-4a9d-90b2-dc6fb3828f6a
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

	column 'Not Started'
		dataType: int64
		formatString: 0
		lineageTag: c841a9f2-5498-4c72-b2e0-03b307e33932
		summarizeBy: sum
		sourceColumn: Not Started

		annotation SummarizationSetBy = Automatic

	column Allotted
		dataType: int64
		formatString: 0
		lineageTag: e6d70d89-80bc-4bab-852f-468fcea456ff
		summarizeBy: sum
		sourceColumn: Allotted

		annotation SummarizationSetBy = Automatic

	column Occupied
		dataType: int64
		formatString: 0
		lineageTag: 555d867d-c5ce-41fd-893a-337ca1146d04
		summarizeBy: sum
		sourceColumn: Occupied

		annotation SummarizationSetBy = Automatic

	column 'Name of the District'
		dataType: string
		lineageTag: 380930c3-c00b-4134-9103-e6ddc8b32f16
		summarizeBy: none
		sourceColumn: Name of the District

		annotation SummarizationSetBy = Automatic

	partition 'AHP All Data' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Abhinay\Downloads\ATAL Project\AHP ULB-Wise Physical Progress.xlsx"), null, true),
				    #"AHP All Data._Sheet" = Source{[Item="AHP All Data.",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"AHP All Data._Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"S.No.", Int64.Type}, {"Name of the District", type text}, {"No. of Dus", Int64.Type}, {"Houses Completed", Int64.Type}, {"Plinth Level", Int64.Type}, {"Structure Status", Int64.Type}, {"Finishing Status", Int64.Type}, {"Total", Int64.Type}, {"Not Started", Int64.Type}, {"Allotted", Int64.Type}, {"Occupied", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

