table MapData
	lineageTag: 47219670-1de6-409c-80c1-caf5bc4d6308

	measure dummy = 0
		formatString: 0
		lineageTag: 89512c6f-13e6-4378-bf60-1cf335ebdbf2

	column 'Sr. No.'
		dataType: string
		lineageTag: 5f963d02-ed80-4e0c-a7b7-25d59df8032e
		summarizeBy: none
		sourceColumn: Sr. No.

		annotation SummarizationSetBy = Automatic

	column 'Office / Scheme Name'
		dataType: string
		lineageTag: a51661c3-bd2a-4e05-bb6b-eece509a8d16
		summarizeBy: none
		sourceColumn: Office / Scheme Name

		annotation SummarizationSetBy = Automatic

	column Indicator
		dataType: string
		lineageTag: fc316707-009d-4b00-96e0-7d47905c1195
		summarizeBy: none
		sourceColumn: Indicator

		annotation SummarizationSetBy = Automatic

	column 'Units (No/ Rs/ Kms)'
		dataType: string
		lineageTag: ab714854-15c5-412f-8515-4106f182bbe4
		summarizeBy: none
		sourceColumn: Units (No/ Rs/ Kms)

		annotation SummarizationSetBy = Automatic

	column 'Type of Data (Absolute No/Percentage/Formula (If any) etc) '
		dataType: string
		lineageTag: 97c2b929-671c-4c91-9d97-d14df8b000a5
		summarizeBy: none
		sourceColumn: "Type of Data (Absolute No/Percentage/Formula (If any) etc) "

		annotation SummarizationSetBy = Automatic

	column 'Frequency Of Data (Monthly/Quarterly/half Yearly/Yearly'
		dataType: string
		lineageTag: c4332caa-6f8f-4f9b-91eb-bdbf387009ec
		summarizeBy: none
		sourceColumn: Frequency Of Data (Monthly/Quarterly/half Yearly/Yearly

		annotation SummarizationSetBy = Automatic

	column 'Lowest geographical unit for data availability (Member/ Household/ Group/Village/Gram Panchayat/Block/District/Division/State)'
		dataType: string
		lineageTag: 9930bf4a-fcbf-43a8-bed6-e7d1cf99cc1c
		summarizeBy: none
		sourceColumn: Lowest geographical unit for data availability (Member/ Household/ Group/Village/Gram Panchayat/Block/District/Division/State)

		annotation SummarizationSetBy = Automatic

	column 'Data Source '
		dataType: string
		lineageTag: bf29f4ca-5520-4634-835f-1afcf9f19300
		summarizeBy: none
		sourceColumn: "Data Source "

		annotation SummarizationSetBy = Automatic

	column 'Department Target (If any) '
		dataType: string
		lineageTag: eeb3b30c-7932-4b49-8fff-ff0e24ed087f
		summarizeBy: none
		sourceColumn: "Department Target (If any) "

		annotation SummarizationSetBy = Automatic

	column 'Data for Baseline '
		dataType: string
		lineageTag: 5c179f8b-32a1-4dd8-8608-772187a63884
		summarizeBy: none
		sourceColumn: "Data for Baseline "

		annotation SummarizationSetBy = Automatic

	column 'Target (Denomenator Data For current month/quarter/year)'
		dataType: string
		lineageTag: 7ea309e0-243c-4ea3-b51d-e1b1d2fda492
		summarizeBy: none
		sourceColumn: Target (Denomenator Data For current month/quarter/year)

		annotation SummarizationSetBy = Automatic

	column 'Achievement(Numerator Data For current month/quarter/year)'
		dataType: string
		lineageTag: 4b73f038-510a-4ceb-9053-8b61c3df3dcc
		summarizeBy: none
		sourceColumn: Achievement(Numerator Data For current month/quarter/year)

		annotation SummarizationSetBy = Automatic

	column Remark
		dataType: string
		lineageTag: b4d7d891-ce6b-4542-91ba-c465d8a79d53
		summarizeBy: none
		sourceColumn: Remark

		annotation SummarizationSetBy = Automatic

	column Achievement
		dataType: double
		lineageTag: f1774038-f497-44a3-9085-ee55e40309cb
		summarizeBy: sum
		sourceColumn: Achievement

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Target
		dataType: double
		lineageTag: 804154fb-99ad-428f-87f9-1a5fd18b9b67
		summarizeBy: sum
		sourceColumn: Target

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Final Result'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 115bd467-8d4e-4a0a-ade2-28f434ccbb57
		summarizeBy: sum
		sourceColumn: Final Result

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition MapData = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Abhinay\Downloads\ATAL Project\Urban dept. KPIs format Revised 29.05.2024.xlsx"), null, true),
				    #"Format 2B_Sheet" = Source{[Item="Format 2B",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Format 2B_Sheet", [PromoteAllScalars=true]),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Promoted Headers", [PromoteAllScalars=true]),
				    #"Promoted Headers2" = Table.PromoteHeaders(#"Promoted Headers1", [PromoteAllScalars=true]),
				    #"Promoted Headers3" = Table.PromoteHeaders(#"Promoted Headers2", [PromoteAllScalars=true])
				in
				    #"Promoted Headers3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

