table Measure
	lineageTag: 951c7091-e94e-47c0-9c64-38c482a16388

	measure Demand = 300000
		formatString: #,0
		lineageTag: 4c1fc34f-94a3-4c6f-b387-c0a0236e8f78

	measure Sanctioned = 302663
		formatString: #,0
		lineageTag: be45dec1-ed94-488e-b527-3b30a55e9f1f

	measure Grounded = 300670
		formatString: #,0
		lineageTag: f9348969-5027-4e7c-ad29-1a153ee6750d

	measure Completed = 253973
		formatString: #,0
		lineageTag: d2a6c4d0-ed2b-40e1-9372-bd31139090e7

	measure Occupied = 242138
		formatString: #,0
		lineageTag: 6216f186-e49c-4274-a770-0659b06c39d7

	measure Committed = 4810.98
		formatString: "₹"#,0.00;-"₹"#,0.00;"₹"#,0.00
		lineageTag: be3b293b-86b9-4ebd-b67f-890849b16b11

		annotation PBI_FormatHint = {"currencyCulture":"ur-IN"}

	measure Released = 4088.81
		formatString: "₹"#,0.00;-"₹"#,0.00;"₹"#,0.00
		lineageTag: f12317f6-5a3f-4838-af11-aaeaaad67036

		annotation PBI_FormatHint = {"currencyCulture":"ur-IN"}

	measure Utilized = 3940.62
		formatString: "₹"#,0.00;-"₹"#,0.00;"₹"#,0.00
		lineageTag: f207609c-1b5b-44ee-ac83-b39b1c81cc1c

		annotation PBI_FormatHint = {"currencyCulture":"ur-IN"}

	measure 'Sanctioned %' = [Sanctioned]/[Demand]
		formatString: 0%;-0%;0%
		lineageTag: db460e9f-7c0d-46f7-bfe7-883c469239a3

	measure 'Grounded %' = [Demand]/[Grounded]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9ff87ada-23bd-4233-8888-ad7b278924d6

	measure 'Completed %' = [Completed]/[Demand]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4f50fc0b-6915-4f98-b2d5-61dca43b5e2d

	measure 'Occupied %' = [Occupied]/[Completed]
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 03d0bb9e-9f77-4e82-bf9c-63033ee4b6e9

	measure 'Released %' = [Released]/[Committed]
		formatString: 0%;-0%;0%
		lineageTag: 7a6d6197-1189-48f2-8287-b77e4553da69

	measure 'Utilized %' = [Utilized]/[Released]
		formatString: 0%;-0%;0%
		lineageTag: 2fb37657-ce51-4d07-800e-d25d0ab7291c

	measure 'progess bar Sanctioned' =
			
			VAR _completed = ROUNDUP([Sanctioned %]*10,0)
			VAR _remaining = 10 - _completed
			RETURN
			REPT("◉",_completed-1) & REPT("○", _remaining + 1)
		lineageTag: ef2d82c9-ae91-460e-bc1d-b5a24e640344

	measure 'progess bar Grounded' =
			
			VAR _completed = ROUNDUP([Grounded %]*10,0)
			VAR _remaining = 10 - _completed
			RETURN
			REPT("◉",_completed-1) & REPT("○", _remaining + 1)
		lineageTag: 09760c46-a77f-407a-ad34-3fc334b14004

	measure 'progess bar Released' =
			
			VAR _completed = ROUNDUP([Released %]*10,0)
			VAR _remaining = 10 - _completed
			RETURN
			REPT("◉",_completed-1) & REPT("○", _remaining + 1)
		lineageTag: 20366826-e15a-4298-ab19-7df621752e1a

	measure 'Completed Progress Bar' =
			
			VAR _completed = ROUNDUP([Completed %]*10,0)
			VAR _remaining = 10 - _completed
			RETURN
			REPT("◉",_completed-1) & REPT("○", _remaining + 1)
		lineageTag: 61484040-a3e3-428e-af77-42de54fdde4c

	measure 'Occupied Progress Bar' =
			
			VAR _completed = ROUNDUP([Occupied %]*10,0)
			VAR _remaining = 10 - _completed
			RETURN
			REPT("◉",_completed-1) & REPT("○", _remaining + 1)
		lineageTag: 7628c391-7d65-4a88-8151-197489764aae

	measure 'Utilized Progress Bar' =
			
			VAR _completed = ROUNDUP([Utilized %]*10,0)
			VAR _remaining = 10 - _completed
			RETURN
			REPT("◉",_completed-1) & REPT("○", _remaining + 1)
		lineageTag: 4e1fc9a8-d321-4b9f-b13d-84cfbe08e179

	partition Measure = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Measures = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Measures", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Measures"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

