table SBM
	lineageTag: 67a9617d-a26f-43d0-9f6a-3883efbbb343

	measure 'Open Defecation free' = DIVIDE(SUM(SBM[City Achieved Certification]), SUM(SBM[Cities in State]), 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7a4b6555-f0a4-4eca-939a-7a44aab4b637

	measure 'Garbage Free City' = DIVIDE(SUM(SBM[Cities Achieved Certificati]), SUM(SBM[Cities in State]), 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 49ece533-00a5-4804-8aab-0b3e3d1fa58e

	column Scheme
		dataType: string
		lineageTag: 6ca65e27-cb76-4227-ba49-28d75d55d7a4
		summarizeBy: none
		sourceColumn: Scheme

		annotation SummarizationSetBy = Automatic

	column District
		dataType: string
		lineageTag: f6a88124-edcd-4658-9eae-e79009bcc495
		summarizeBy: none
		sourceColumn: District

		annotation SummarizationSetBy = Automatic

	column 'Total City'
		dataType: int64
		formatString: 0
		lineageTag: c80b8096-133e-4341-b5b0-2630db687668
		summarizeBy: sum
		sourceColumn: Total City

		annotation SummarizationSetBy = Automatic

	column 'City Achieved Certification'
		dataType: int64
		formatString: 0
		lineageTag: 3c6fc564-6c1f-4621-8465-bc9ca688385e
		summarizeBy: sum
		sourceColumn: City Achieved Certification

		annotation SummarizationSetBy = Automatic

	column 'Cities in State'
		dataType: int64
		formatString: 0
		lineageTag: 94dcc321-89e4-4870-9bee-a82926371213
		summarizeBy: sum
		sourceColumn: Cities in State

		annotation SummarizationSetBy = Automatic

	column 'Cities Achieved Certificati'
		dataType: int64
		formatString: 0
		lineageTag: fe3e0f65-15e3-499f-8ed3-4d7c76ad8af8
		summarizeBy: sum
		sourceColumn: Cities Achieved Certificati

		annotation SummarizationSetBy = Automatic

	partition SBM = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Abhinay\Downloads\ATAL Project\district name_CG.xlsx"), null, true),
				    SBM_Sheet = Source{[Item="SBM",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(SBM_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Scheme", type text}, {"District", type text}, {"Total City", Int64.Type}, {"City Achieved Certification", Int64.Type}, {"Cities in State", Int64.Type}, {"Cities Achieved Certificati", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

