table 'ULB (Top N) Measures'
	lineageTag: 59042313-0c7b-499e-97d3-6d6471adfd0e

	measure 'ULB Rank by Records' =
			
			RANKX(ALL('ULB-Wise Progress'[ULB Name]), [Completed Measure (ULB)] , , DESC,Dense)
		formatString: 0
		lineageTag: 7971af4d-d359-4e01-9dd3-c8cc177e5d17

	measure 'TOP10 ULB Rank' =
			
			IF('ULB (Top N) Measures'[ULB Rank by Records]<=SELECTEDVALUE('ULB (Top N) Measures'[Value]),1,0)
		formatString: 0
		lineageTag: ea6672da-393c-47b9-8806-6cea2eabcda0

	measure 'ULB Top10 Title' = Selectedvalue('ULB (Top N) Measures'[Metric]) & " ULB Name by " & SELECTEDVALUE('ULB Parameter'[Value4])
		lineageTag: 23350cdc-a031-4c98-bd32-e472736ea1b9

	column Value
		dataType: int64
		formatString: 0
		lineageTag: b0ef3612-3ff1-4846-88df-c62553aa196f
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Metric
		dataType: string
		lineageTag: 3bb852da-b3d6-42da-b19a-b12d665a8f94
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

	partition 'ULB (Top N) Measures' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlXSUQrJL1AwVYrViVYyNIBygQwwHyYNZMTGAgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Value = _t, Metric = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Value", Int64.Type}, {"Metric", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

