table 'IM GMV (Last 7 Days Line)'
	lineageTag: e71abd0e-88da-4464-8b27-d1c61ae23874

	column COUNT_id
		dataType: double
		sourceProviderType: double
		lineageTag: 695bc033-757d-4098-9242-1dedfd4dd70a
		summarizeBy: sum
		sourceColumn: COUNT_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column created_at_ist
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 8006df33-c23b-40e4-a8d0-5de12ee11a5b
		summarizeBy: none
		sourceColumn: created_at_ist

		annotation SummarizationSetBy = Automatic

	column time_period
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 37aa0774-ccbf-422c-b416-4e568ba6a4bb
		summarizeBy: none
		sourceColumn: time_period

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: bd8328ab-c761-447d-b2f3-a97768f57e14
		summarizeBy: sum
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 0553d1cd-9edd-40b5-96c1-21eab4ac2ae5
		summarizeBy: none
		sourceColumn: Week
		sortByColumn: created_at_ist

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'IM GMV (Last 7 Days Line)' = m
		mode: directQuery
		queryGroup: 'IM\IM-Last 7 Days\IM-Sales\IM-GMV'
		source = ```
				let   
				    // Get current date and time in UTC
				    TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				    // Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				    TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				    // Get today's date in IST (removes the time part)
				
				    TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				    TodayDate = DateTime.Date(TodaysDateTime),
				
				    // Get the date 7 days ago in IST
				    Last7Days = TodayDate - #duration(7, 0, 0, 0),
				
				    // Last 7 days current week to 12:00 AM IST
				    StartOfLast7Days = DateTime.FromText(Date.ToText(Last7Days) & " 00:00:00"),
				    StartOfLast7DaysFormatted = DateTime.ToText(StartOfLast7Days, "yyyy-MM-dd HH:mm:ss"),
				    CurrentDate = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				    EndofCurrentDateFormatted = DateTime.ToText(CurrentDate, "yyyy-MM-dd HH:mm:ss"),
				
				    // Last 7 days previous week to 12:00 AM IST
				    LastWeekStartDateTime = StartOfLast7Days - #duration(7, 0, 0, 0),
				    StartOfLastWeek = DateTime.FromText(Date.ToText(DateTime.Date(LastWeekStartDateTime)) & " 00:00:00"),
				    StartOfLastWeekFormatted = DateTime.ToText(StartOfLastWeek, "yyyy-MM-dd HH:mm:ss"),
				    EndofLastWeekFormatted = StartOfLast7DaysFormatted,
				
				    TableName = IMTableName,
				
				    Query = "let current_week = " & TableName & " 
				| where created_at_ist >= datetime('"& StartOfLast7DaysFormatted &"') 
				| where created_at_ist < datetime('"& EndofCurrentDateFormatted &"') 
				| extend counter = case(order_level != 'ORDER_LEVEL_LEAF' or isempty(order_level), 1, 0) 
				| where dp_order_type == 'INSTAMART' and (status == 'DELIVERY_DELIVERED' or status == 'COMPLETED') 
				| summarize COUNT_id = sum(gmv) by bin(created_at_ist, 1d)
				| extend time_period='Daily Trend'
				| project COUNT_id, created_at_ist, time_period;
				let last_week = " & TableName & " 
				| where created_at_ist >= datetime('"& StartOfLastWeekFormatted &"') 
				| where created_at_ist < datetime('"& EndofLastWeekFormatted &"') 
				| where dp_order_type == 'INSTAMART' and (status == 'DELIVERY_DELIVERED' or status == 'COMPLETED')
				| extend created_at_ist = datetime_add('hour', 168, created_at_ist)
				| summarize COUNT_id = sum(gmv) by bin(created_at_ist, 1d)
				| extend time_period='1 Week Ago'
				| project COUNT_id, created_at_ist, time_period;
				current_week
				| union last_week",
				    // Get data from Azure Data Explorer with the dynamic query
				    Source = AzureDataExplorer.Contents(Cluster,DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				   #"Inserted Day of Week" = Table.AddColumn(Source, "Day of Week", each Date.DayOfWeek([created_at_ist]), Int64.Type),
				    #"Added Conditional Column" = Table.AddColumn(#"Inserted Day of Week", "Week", each if [Day of Week] = 1 then "Mon" else if [Day of Week] = 2 then "Tue" else if [Day of Week] = 3 then "Wed" else if [Day of Week] = 4 then "Thur" else if [Day of Week] = 5 then "Fri" else if [Day of Week] = 6 then "Sat" else if [Day of Week] = 0 then "Sun" else null),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column",{{"created_at_ist", type datetime}, {"Week", type text}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

