table 'ALL Measures'
	lineageTag: d5f31804-b7f4-48c7-a67c-d4d190f15e1d

	measure 'AOV 7 Days' =
			
			var totalgmv = SUMX('Food AOV Count Decomposition Tree- Last 7 Days', 'Food AOV Count Decomposition Tree- Last 7 Days'[GroupAvgGmv] * 'Food AOV Count Decomposition Tree- Last 7 Days'[GroupCount])
			var totalcount = SUM('Food AOV Count Decomposition Tree- Last 7 Days'[GroupCount])
			RETURN
			DIVIDE(totalgmv, totalcount, 0)
		displayFolder: Food\3-Last 7 Days
		lineageTag: 353bb10b-ba9e-4348-a311-2bd63a1f8994

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AOV =
			
			var totalgmv = SUMX('Food AOV Count Decomposition Tree- Today', 'Food AOV Count Decomposition Tree- Today'[GroupAvgGmv] * 'Food AOV Count Decomposition Tree- Today'[GroupCount])
			var totalcount = SUM('Food AOV Count Decomposition Tree- Today'[GroupCount])
			RETURN
			DIVIDE(totalgmv, totalcount, 0)
		displayFolder: Food\1-Today
		lineageTag: 891e04fd-3849-4e39-8414-f70b76e64232

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOV yesterday' =
			
			var totalgmv = SUMX('Food AOV Count Decomposition Tree- Yesterday', 'Food AOV Count Decomposition Tree- Yesterday'[GroupAvgGmv] * 'Food AOV Count Decomposition Tree- Yesterday'[GroupCount])
			var totalcount = SUM('Food AOV Count Decomposition Tree- Yesterday'[GroupCount])
			RETURN
			DIVIDE(totalgmv, totalcount, 0)
		displayFolder: Food\2-Yesterday
		lineageTag: f3097b8d-b4db-41fb-9fb4-abc4d2feb930

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CDC 7 Days' =
			
			var totalcdc = SUMX('Food CDC% Decomposition Tree- Last 7 Days', 'Food CDC% Decomposition Tree- Last 7 Days'[GroupCDC] * 'Food CDC% Decomposition Tree- Last 7 Days'[GroupCount])
			var totalcount = SUM('Food CDC% Decomposition Tree- Last 7 Days'[GroupCount])
			RETURN
			DIVIDE(totalcdc, totalcount, 0)
		displayFolder: Food\3-Last 7 Days
		lineageTag: c8fca810-3704-4ebe-ba56-5be39fa185e9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CDC Today' =
			
			var totalgmv = SUMX('Food CDC% Decomposition Tree- Today', 'Food CDC% Decomposition Tree- Today'[GroupCDC] * 'Food CDC% Decomposition Tree- Today'[GroupCount])
			var totalcount = SUM('Food CDC% Decomposition Tree- Today'[GroupCount])
			RETURN
			DIVIDE(totalgmv, totalcount, 0)
		displayFolder: Food\1-Today
		lineageTag: 6a529767-cf4c-47fe-be70-3153d35e2c4f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CDC Yesterday' =
			
			var totalcdc = SUMX('Food CDC% Decomposition Tree- Yesterday', 'Food CDC% Decomposition Tree- Yesterday'[GroupCDC] * 'Food CDC% Decomposition Tree- Yesterday'[GroupCount])
			var totalcount = SUM('Food CDC% Decomposition Tree- Yesterday'[GroupCount])
			RETURN
			DIVIDE(totalcdc, totalcount, 0)
		displayFolder: Food\2-Yesterday
		lineageTag: 244f01f4-13a7-441e-bc32-59cdb87b3ba9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RDC 4 Weeks' =
			
			var totalcdc = SUMX('Food RDC% DecompositionTree- Last 4 Weeks', 'Food RDC% DecompositionTree- Last 4 Weeks'[GroupRDC] * 'Food RDC% DecompositionTree- Last 4 Weeks'[GroupCount])
			var totalcount = SUM('Food RDC% DecompositionTree- Last 4 Weeks'[GroupCount])
			RETURN
			DIVIDE(totalcdc, totalcount, 0)
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: 48d1f040-b5ac-4230-b335-644c43b00598

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RDC 7 Days' =
			
			var totalcdc = SUMX('Food RDC% DecompositionTree- Last 7 Days', 'Food RDC% DecompositionTree- Last 7 Days'[GroupRDC] * 'Food RDC% DecompositionTree- Last 7 Days'[GroupCount])
			var totalcount = SUM('Food RDC% DecompositionTree- Last 7 Days'[GroupCount])
			RETURN
			DIVIDE(totalcdc, totalcount, 0)
		displayFolder: Food\3-Last 7 Days
		lineageTag: abcb0cf2-4b68-44c3-bf96-6e7e671c1206

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RDC Today' =
			
			var totalrdc = SUMX('Food RDC% Decompotion Tree- Today', 'Food RDC% Decompotion Tree- Today'[GroupRDC] * 'Food RDC% Decompotion Tree- Today'[GroupCount])
			var totalcount = SUM('Food RDC% Decompotion Tree- Today'[GroupCount])
			RETURN
			DIVIDE(totalrdc, totalcount, 0)
		displayFolder: Food\1-Today
		lineageTag: b00830f8-67f9-477e-b10c-58213018b009

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RDC Yesterday' =
			
			var totalrdc = SUMX('Food RDC% Decompotion Tree- Yesterday', 'Food RDC% Decompotion Tree- Yesterday'[GroupRDC] * 'Food RDC% Decompotion Tree- Yesterday'[GroupCount])
			var totalcount = SUM('Food RDC% Decompotion Tree- Yesterday'[GroupCount])
			RETURN
			DIVIDE(totalrdc, totalcount, 0)
		displayFolder: Food\2-Yesterday
		lineageTag: df6a2b63-07cd-470a-b9ef-117c0c949efe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SDC Today' =
			
			var totalsdc = SUMX('Food SDC% Decomposition Tree- Today', 'Food SDC% Decomposition Tree- Today'[GroupSDC] * 'Food SDC% Decomposition Tree- Today'[GroupCount])
			var totalcount = SUM('Food SDC% Decomposition Tree- Today'[GroupCount])
			RETURN
			DIVIDE(totalsdc, totalcount, 0)
		displayFolder: Food\1-Today
		lineageTag: 8ed28bcb-fe0b-4299-b6fe-b16230047a3c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SDC 4 Weeks' =
			
			var totalsdc = SUMX('Food SDC% Decomposition Tree-Last 4 Weeks', 'Food SDC% Decomposition Tree-Last 4 Weeks'[GroupSDC] * 'Food SDC% Decomposition Tree-Last 4 Weeks'[GroupCount])
			var totalcount = SUM('Food SDC% Decomposition Tree-Last 4 Weeks'[GroupCount])
			RETURN
			DIVIDE(totalsdc, totalcount, 0)
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: f77fddbc-cd32-4721-badf-c3f720184985

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SDC 7 Days' =
			
			var totalsdc = SUMX('Food SDC% Decomposition Tree-Last 7 Days', 'Food SDC% Decomposition Tree-Last 7 Days'[GroupSDC] * 'Food SDC% Decomposition Tree-Last 7 Days'[GroupCount])
			var totalcount = SUM('Food SDC% Decomposition Tree-Last 7 Days'[GroupCount])
			RETURN
			DIVIDE(totalsdc, totalcount, 0)
		displayFolder: Food\3-Last 7 Days
		lineageTag: 15906aaa-97f7-4e92-9359-526e5e27d01b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SDC Yesterday' =
			
			var totalsdc = SUMX('Food SDC% Decomposition Tree-Yesterday', 'Food SDC% Decomposition Tree-Yesterday'[GroupSDC] * 'Food SDC% Decomposition Tree-Yesterday'[GroupCount])
			var totalcount = SUM('Food SDC% Decomposition Tree-Yesterday'[GroupCount])
			RETURN
			DIVIDE(totalsdc, totalcount, 0)
		displayFolder: Food\2-Yesterday
		lineageTag: 5b6be87e-c523-45b3-bf6b-30000aa901db

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Arrow AOV Color Last 4 Weeks' = ```
			
			IF(
			                MAX('Food WOW% AOV-Last 4 Weeks'[print_0]) > 0, 
			                "limegreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: 7442c4ca-68de-4505-9a9c-e8f69e2f36d3

	measure 'Arrow WOW% AOV Last 4 Weeks' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% AOV-Last 4 Weeks'[print_0]) < 0, Down, IF(MAX('Food WOW% AOV-Last 4 Weeks'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: 25aa8fba-41da-44e3-9b45-083ca99dcb3b

	measure 'Arrow AOV Color Last 7 Days' = ```
			
			IF(
			                MAX('Food WOW% AOV-Last 7 Days'[print_0]) > 0, 
			                "limegreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: 52232680-4592-437f-b7a6-32db3fc24dc0

	measure 'Arrow WOW% AOV Last 7 Days' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% AOV-Last 7 Days'[print_0]) < 0, Down, IF(MAX('Food WOW% AOV-Last 7 Days'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: ba5828e1-9b07-4bdd-bb3f-50263b3072fb

	measure 'Arrow AOV Color' = ```
			
			IF(
			                MAX('Food WOW% AOV-Today'[print_0]) > 0, 
			                "limegreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: Food\1-Today
		lineageTag: 8fcb3887-25b5-4b76-87be-266e88d43dcb

	measure 'Arrow WOW% AOV' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% AOV-Today'[print_0]) < 0, Down, IF(MAX('Food WOW% AOV-Today'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\1-Today
		lineageTag: 59608eaa-1cf1-473c-870e-4edc6daf6796

	measure 'Arrow AOV Color yesterday' = ```
			
			IF(
			                MAX('Food WOW% AOV-Yesterday'[print_0]) > 0, 
			                "limegreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: Food\2-Yesterday
		lineageTag: 3e34e00b-ef18-456a-a659-74db9f55a2d4

	measure 'Arrow WOW% AOV-yesterday' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% AOV-Yesterday'[print_0]) < 0, Down, IF(MAX('Food WOW% AOV-Yesterday'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\2-Yesterday
		lineageTag: 2c596b51-9cf9-43e8-b641-8d6cac8d5936

	measure 'Arrow Cancelled Color Last 4 Weeks' = ```
			
			    
			                IF(
			                MAX('Food WOW% Cancelled- Last 4 Weeks'[print_0]) > 0, 
			                "tomato",  // If the value is positive, return red
			                "limeGreen"  // If the value is negative, return green
			               )
			
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: ecbf240c-4f94-45d5-a773-2165d88d11ba

	measure 'Arrow WOW% cancelled Last 4 Weeks' = ```
			
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR Down = UNICHAR(9660)  // Down
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% Cancelled- Last 4 Weeks'[print_0]) < 0, Down, IF(MAX('Food WOW% Cancelled- Last 4 Weeks'[print_0])> 0, Up, line))
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: 8fe03b66-2d59-48eb-b103-d3e59987088c

	measure 'Arrow Cancelled Color Last 7 Days' = ```
			
			    
			                IF(
			                MAX('Food WOW% Cancelled- Last 7 Days'[print_0]) > 0, 
			                "limegreen",  // If the value is positive, return red
			                "tomato"  // If the value is negative, return green
			               )
			
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: 1154b54f-d05b-4cbd-bfde-8b53360616c6

	measure 'Arrow WOW% cancelled Last 7 Days' = ```
			
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR Down = UNICHAR(9660)  // Down
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% Cancelled- Last 7 Days'[print_0]) < 0, Down, IF(MAX('Food WOW% Cancelled- Last 7 Days'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: ad684ade-0cc8-4dca-bccd-0698ca9d4d47

	measure 'Arrow Cancelled Color' = ```
			
			    
			                IF(
			                MAX('Food WOW% Cancelled- Today'[print_0]) > 0, 
			                "tomato",  // If the value is positive, return red
			                "limegreen"  // If the value is negative, return green
			               )
			
			```
		displayFolder: Food\1-Today
		lineageTag: b85e6619-f449-4621-9d62-b5170eec62b4

	measure 'Arrow WOW% cancelled' = ```
			
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR Down = UNICHAR(9660)  // Down
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% Cancelled- Today'[print_0]) < 0, Down, IF(MAX('Food WOW% Cancelled- Today'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\1-Today
		lineageTag: 406edfc5-1153-47ed-8da5-d80db260a05b

	measure 'Arrow Cancelled Color Yesterday' = ```
			
			    
			                IF(
			                MAX('Food WOW% Cancelled- Yesterday'[print_0]) > 0, 
			                "tomato",  // If the value is positive, return red
			                "limeGreen"  // If the value is negative, return green
			               )
			
			```
		displayFolder: Food\2-Yesterday
		lineageTag: dcef4e88-dfef-4294-8aa6-a08235179b90

	measure 'Arrow WOW% cancelled- yesterday' = ```
			
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR Down = UNICHAR(9660) //Down
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(Max('Food WOW% Cancelled- Yesterday'[print_0]) < 0, Down, IF(Max('Food WOW% Cancelled- Yesterday'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\2-Yesterday
		lineageTag: 05069884-5aaf-4216-b861-eb1f49dcaa8b

	measure 'Arrow CDC Color Last 4 weeks' = ```
			
			    
			                IF(
			                MAX('Food WOW% CDC-Last 4 Weeks'[print_0]) > 0, 
			                "Tomato",  // If the value is positive, return green
			                "LimeGreen"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: 1f8f712c-55ed-46db-a503-2d0672edac74

	measure 'Arrow WOW% CDC Last 4 Weeks' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% CDC-Last 4 Weeks'[print_0]) < 0, Down, IF(MAX('Food WOW% CDC-Last 4 Weeks'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: caedde86-3b14-4f0d-a1b5-2b900717f640

	measure 'Arrow CDC Color Last 7 Days' = ```
			
			    
			                IF(
			                MAX('Food WOW% CDC-Last 7 Days'[print_0]) > 0, 
			                "tomato",  // If the value is positive, return green
			                "limeGreen"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: d858f5e2-9fa3-4ba4-a594-4e36c8e96609

	measure 'Arrow WOW% CDC Last 7 Days' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% CDC-Last 7 Days'[print_0]) < 0, Down, IF(MAX('Food WOW% CDC-Last 7 Days'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: a5f9b293-8255-4cea-b66a-47b7135387db

	measure 'Arrow CDC Color' = ```
			
			    
			                IF(
			                MAX('Food WOW% CDC-Today'[print_0]) > 0, 
			                "tomato",  // If the value is positive, return green
			                "limeGreen"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\1-Today
		lineageTag: 0c491537-8393-4baf-af32-f537d2e9e934

	measure 'Arrow WOW% CDC' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% CDC-Today'[print_0]) < 0, Down, IF(MAX('Food WOW% CDC-Today'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\1-Today
		lineageTag: 27101189-a3ce-4274-a6ab-02a80c36b70b

	measure 'Arrow CDC Color Yesterday' = ```
			
			    
			                IF(
			                MAX('Food WOW% CDC-Yesterday'[print_0]) > 0, 
			                "tomato",  // If the value is positive, return green
			                "limeGreen"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\2-Yesterday
		lineageTag: 1973e835-b1ca-4e99-b470-e68170893155

	measure 'Arrow WOW% CDC Yesterday' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% CDC-Yesterday'[print_0]) < 0, Down, IF(MAX('Food WOW% CDC-Yesterday'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\2-Yesterday
		lineageTag: 9fa72540-7814-4928-b798-105bd2862f6b

	measure 'Arrow Order Color Last 4 Weeks' = ```
			
			    
			                IF(
			                MAX('Food WOW% Completed Order-Last 4 weeks'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: 64a0f4de-042b-43db-b7aa-336404f64721

	measure 'Arrow WOW% Order Last 4 Weeks' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% Completed Order-Last 4 weeks'[print_0]) < 0, Down, IF(MAX('Food WOW% Completed Order-Last 4 weeks'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: 8f30795a-7b94-4c26-ac69-1ce7cb863300

	measure 'Arrow Order Color Last 7 Days' = ```
			
			    
			                IF(
			                MAX('Food WOW% Completed Order-Last 7 Days'[print_0]) > 0, 
			                "LimeGreen",  // If the value is positive, return green
			                "Tomato"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: 3341b998-963b-4db3-a7f4-9e28fd83c4f2

	measure 'Arrow WOW% Order Last 7 Days' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% Completed Order-Last 7 Days'[print_0]) < 0, Down, IF(MAX('Food WOW% Completed Order-Last 7 Days'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: 98e3e4c1-8a87-458a-b241-954ca9d842ac

	measure 'Arrow Order Color yesterday' = ```
			
			    
			                IF(
			                MAX('Food WOW% Completed Order-Yesterday'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\2-Yesterday
		lineageTag: 1eb85e4d-5812-4220-b49a-e7fc8875f373

	measure 'Arrow WOW% Order- yesterday' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% Completed Order-Yesterday'[print_0]) < 0, Down, IF(MAX('Food WOW% Completed Order-Yesterday'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\2-Yesterday
		lineageTag: 663ff148-1210-47c2-83a4-3ff4c06fb5f6

	measure 'Arrow Order Color' = ```
			
			    
			                IF(
			                MAX('Food WOW% Completed Orders Today'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\1-Today
		lineageTag: 2e52283f-0d22-4a53-aca6-c60a9e620677

	measure 'Arrow WOW% Order' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% Completed Orders Today'[print_0]) < 0, Down, IF(MAX('Food WOW% Completed Orders Today'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\1-Today
		lineageTag: 609b5822-841f-4764-adcb-419c622260da

	measure 'Arrow FTR Color Last 4 Weeks' = ```
			
			    
			                IF(
			                MAX('Food WOW% FTR-Last 4 Weeks'[print_0]) > 0, 
			                "LimeGreen",  // If the value is positive, return green
			                "Tomato"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: 25e1aab6-4606-48db-9618-50cb4d02e218

	measure 'Arrow WOW% FTR Last 4 Weeks' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% FTR-Last 4 Weeks'[print_0]) < 0, Down, IF(MAX('Food WOW% FTR-Last 4 Weeks'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: 3a290b34-d2d6-49ed-9ef4-dba16564e965

	measure 'Arrow FTR Color Last 7 Days' = ```
			
			    
			                IF(
			                MAX('Food WOW% FTR-Last 7 Days'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: 1b8703d7-04e7-4d17-b85b-0a2fcc6a0576

	measure 'Arrow WOW% FTR Last 7 Days' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% FTR-Last 7 Days'[print_0]) < 0, Down, IF(MAX('Food WOW% FTR-Last 7 Days'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: ec5b459c-d2d2-4443-ab6d-e0e27db6cf5d

	measure 'Arrow FTR Color' = ```
			
			    
			                IF(
			                MAX('Food WOW% FTR-Today'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\1-Today
		lineageTag: c325c680-671b-46a8-8d04-15c56a24b204

	measure 'Arrow WOW% FTR' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% FTR-Today'[print_0]) < 0, Down, IF(MAX('Food WOW% FTR-Today'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\1-Today
		lineageTag: 65674520-a898-4924-9472-d4d1224e172b

	measure 'Arrow FTR Color Yesterday' = ```
			
			    
			                IF(
			                MAX('Food WOW% FTR-Yesterday'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\2-Yesterday
		lineageTag: 1f7f6e9f-398d-4c88-928e-42c8d0093cd0

	measure 'Arrow WOW% FTR yesterday' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% FTR-Yesterday'[print_0]) < 0, Down, IF(MAX('Food WOW% FTR-Yesterday'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\2-Yesterday
		lineageTag: 5e956314-6f1e-4313-a149-78302b40face

	measure 'Arrow FTU Color Last 4 Weeks' = ```
			
			    
			                IF(
			                MAX('Food WOW% FTU-Last 4 Weeks'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: 79ae5955-6f0b-4d2a-b76f-52a8bf2a16fd

	measure 'Arrow WOW% FTU Last 4 Weeks' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% FTU-Last 4 Weeks'[print_0]) < 0, Down, IF(MAX('Food WOW% FTU-Last 4 Weeks'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: dda5ad41-20ef-40a5-a5c0-354d20e561b5

	measure 'Arrow FTU Color Last 7 Days' = ```
			
			    
			                IF(
			                MAX('Food WOW% FTU-Last 7 Days'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: 419ac1e1-f90d-4119-bb25-37956eeed6dd

	measure 'Arrow WOW% FTU Last 7 Days' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% FTU-Last 7 Days'[print_0]) < 0, Down, IF(MAX('Food WOW% FTU-Last 7 Days'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: d9fe46df-ebb0-4daf-b8b5-7fcb24f4083c

	measure 'Arrow FTU Color' = ```
			
			    
			                IF(
			                MAX('Food WOW% FTU-Today'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\1-Today
		lineageTag: 9d96be9b-00f8-48b9-a085-8314b17d2cce

	measure 'Arrow WOW% FTU' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% FTU-Today'[print_0]) < 0, Down, IF(MAX('Food WOW% FTU-Today'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\1-Today
		lineageTag: aa973063-3d2c-460d-9853-55ee7cf8723d

	measure 'Arrow FTU Color Yesterday' = ```
			
			    
			                IF(
			                MAX('Food WOW% FTU-Yesterday'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\2-Yesterday
		lineageTag: bb8ef427-4ecb-4da0-9baf-fddf5b3f4f73

	measure 'Arrow WOW% FTU Yesterday' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% FTU-Yesterday'[print_0]) < 0, Down, IF(MAX('Food WOW% FTU-Yesterday'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\2-Yesterday
		lineageTag: 811bd1bf-d468-4d57-8bd4-98a77bc35ec2

	measure 'Arrow GMV Color Last 4 Weeks' = ```
			
			                IF(
			                MAX('Food WOW% GMV- Last 4 Weeks'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: 0fdc441f-fe9f-4d94-9094-fb01ca70b625

	measure 'Arrow WOW% gmv Last 4 Weeks' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% GMV- Last 4 Weeks'[print_0]) < 0, Down, IF(MAX('Food WOW% GMV- Last 4 Weeks'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: d7d92bc5-3131-4cd2-b9d9-fcd51b9421ff

	measure 'Arrow GMV Color Last 7 Days' = ```
			
			                IF(
			                MAX('Food WOW% GMV- Last 7 Days'[print_0]) > 0, 
			                "LimeGreen",  // If the value is positive, return green
			                "Tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: 54f8952c-a4d7-45d1-85b0-5ecb9ae3c9c2

	measure 'Arrow WOW% gmv Last 7 Days' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% GMV- Last 7 Days'[print_0]) < 0, Down, IF(MAX('Food WOW% GMV- Last 7 Days'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: 138ec208-3eba-44ff-990d-3e44e2684c97

	measure 'Arrow GMV Color' = ```
			
			                IF(
			                MAX('Food WOW% GMV-Today'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: Food\1-Today
		lineageTag: 158355b7-0a33-4e61-a9f9-78b9d9ca439d

	measure 'Arrow WOW% gmv' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% GMV-Today'[print_0]) < 0, Down, IF(MAX('Food WOW% GMV-Today'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\1-Today
		lineageTag: 1519d952-7a71-4281-bde0-a93d34e12f35

	measure 'Arrow GMV Color yesterday' = ```
			
			                IF(
			                MAX('Food WOW% GMV-Yesterday'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: Food\2-Yesterday
		lineageTag: 2738ca6c-b943-4470-880f-e785008f4966

	measure 'Arrow WOW% GMV yesterday' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% GMV-Yesterday'[print_0]) < 0, Down, IF(MAX('Food WOW% GMV-Yesterday'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\2-Yesterday
		lineageTag: de9f6857-1d98-449c-82a8-982aca24b835

	measure 'Arrow RDC Color Last 4 Weeeks' = ```
			
			                IF(
			                MAX('Food WOW% RDC- Last 4 Weeks'[print_0]) > 0, 
			                "tomato",  // If the value is positive, return green
			                "limeGreen"  // If the value is negative, return red
			               )
			
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: c4a7cb46-f423-4954-8140-9ebc78aa83b4

	measure 'Arrow WOW% RDC Last 4 Weeks' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% RDC- Last 4 Weeks'[print_0]) < 0, Down, IF(MAX('Food WOW% RDC- Last 4 Weeks'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: ba6397b1-c90e-4c48-9fa1-7756a01725a7

	measure 'Arrow RDC Color Last 7 Days' = ```
			
			                IF(
			                MAX('Food WOW% RDC- Last 7 Days'[print_0]) > 0, 
			                "Tomato",  // If the value is positive, return green
			                "LimeGreen"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: 7c8d498d-593b-4670-a6d5-85be5fdce05c

	measure 'Arrow WOW% RDC Last 7 Days' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% RDC- Last 7 Days'[print_0]) < 0, Down, IF(MAX('Food WOW% RDC- Last 7 Days'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: ca99688a-6e3e-4caf-98fe-98c32920deb9

	measure 'Arrow RDC Color' = ```
			
			                IF(
			                MAX('Food WOW% RDC-Today'[print_0]) > 0, 
			                "tomato",  // If the value is positive, return green
			                "limegreen"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: Food\1-Today
		lineageTag: 88946da6-5a22-432e-bcb2-26fe8f6d23b0

	measure 'Arrow WOW% RDC' = ```
			
			    VAR Down = UNICHAR(9660) // down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% RDC-Today'[print_0]) < 0, Down, IF(MAX('Food WOW% RDC-Today'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\1-Today
		lineageTag: d5a6feed-de24-4a0a-b6d0-7db49c589ace

	measure 'Arrow RDC Color Yesterday' = ```
			
			                IF(
			                MAX('Food WOW% RDC-Yesterday'[print_0]) > 0, 
			                "tomato",  // If the value is positive, return green
			                "limeGreen"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: Food\2-Yesterday
		lineageTag: ef8643ab-e916-4dc1-bd25-ff026b425bc7

	measure 'Arrow WOW% RDC Yesterday' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% RDC-Yesterday'[print_0]) < 0, Down, IF(MAX('Food WOW% RDC-Yesterday'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\2-Yesterday
		lineageTag: 06e6dfbf-33d8-41b8-8209-0da6d0cda86b

	measure 'Arrow SDC Color Last 4 weeks' = ```
			
			                IF(
			                MAX('Food WOW% SDC-Last 4 Weeks'[print_0]) > 0, 
			                "tomato",  // If the value is positive, return green
			                "limeGreen"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: c355b5de-89e2-4c7f-ba26-b87819823e01

	measure 'Arrow WOW% SDC Last 4 Weeks' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% SDC-Last 4 Weeks'[print_0]) < 0, Down, IF(MAX('Food WOW% SDC-Last 4 Weeks'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: 256c453a-f194-46c4-8fa9-f2089276ebf3

	measure 'Arrow SDC Color Last 7 Days' = ```
			
			                IF(
			                MAX('Food WOW% SDC-Last 7 Days'[print_0]) > 0, 
			                "tomato",  // If the value is positive, return green
			                "limeGreen"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: 7a71b9a8-2e38-4bb2-8ad6-38d716aac2fb

	measure 'Arrow WOW% SDC Last 7 Days' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% SDC-Last 7 Days'[print_0]) < 0, Down, IF(MAX('Food WOW% SDC-Last 7 Days'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\3-Last 7 Days
		lineageTag: 0be8544c-99d3-446d-8f4e-c1ca4f73e5a3

	measure 'Arrow SDC Color' = ```
			
			                IF(
			                MAX('Food WOW% SDC-Today'[print_0]) > 0, 
			                "tomato",  // If the value is positive, return green
			                "limegreen"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: Food\1-Today
		lineageTag: 87c7818a-9644-40ed-989c-37f8c6ae391b

	measure 'Arrow WOW% SDC' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% SDC-Today'[print_0]) < 0, Down, IF(MAX('Food WOW% SDC-Today'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\1-Today
		lineageTag: 235fcda3-6a2b-4f7a-9d7b-03e5a88ba453

	measure 'Arrow SDC Color yesterday' = ```
			
			                IF(
			                MAX('Food WOW% SDC-Yesterday'[print_0]) > 0, 
			                "tomato",  // If the value is positive, return green
			                "limeGreen"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: Food\2-Yesterday
		lineageTag: 49dd1d72-4fa6-4ed7-bbd8-57787d8d30ad

	measure 'Arrow WOW% SDC yesterday' = ```
			
			    VAR Down = UNICHAR(9660) //down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('Food WOW% SDC-Yesterday'[print_0]) < 0, Down, IF(MAX('Food WOW% SDC-Yesterday'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: Food\2-Yesterday
		lineageTag: 6b55c83e-7ef6-47f5-9e7a-d39ae4f11688

	measure 'IM AOV' =
			
			var totalgmv = SUM('IM AOV Count Decomposition Tree- Today'[GroupGmv])
			var totalcount = SUM('IM AOV Count Decomposition Tree- Today'[GroupCounter])
			RETURN
			DIVIDE(totalgmv, totalcount, 0)
		displayFolder: InstaMart\1-Today
		lineageTag: fc27e8bb-904f-407f-9778-2dc4c6cb9137

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'IM AOV Yesterday' =
			
			var totalgmv = SUM('IM AOV Count Decomposition Tree- Yesterday'[GroupGmv])
			var totalcount = SUM('IM AOV Count Decomposition Tree- Yesterday'[GroupCounter])
			RETURN
			DIVIDE(totalgmv, totalcount, 0)
		displayFolder: InstaMart\2-Yesterday
		lineageTag: 5aeba3e2-0441-425a-98bb-0e7485dc64aa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Arrow AOV Color IM-L4W' = ```
			
			IF(
			                MAX('IM WOW% AOV-Last 4 Weeks'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: InstaMart\4-Last 4 Weeks
		lineageTag: 88247a4a-3a66-4975-b457-d550ec6f3137

	measure 'Arrow WOW% AOV IM -L4D' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('IM WOW% AOV-Last 4 Weeks'[print_0]) < 0, Down, IF(MAX('IM WOW% AOV-Last 4 Weeks'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: InstaMart\4-Last 4 Weeks
		lineageTag: 80c2864b-3866-434b-9d50-ab8ccb97e0a2

	measure 'Arrow AOV Color IM-L7D' = ```
			
			IF(
			                MAX('IM WOW% AOV-Last 7 Days'[print_0]) > 0, 
			                "limegreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: InstaMart\3-Last 7 Days
		lineageTag: dce5fe13-5fa0-4276-bbf8-1b6e01152a10

	measure 'Arrow WOW% AOV IM -L7D' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('IM WOW% AOV-Last 7 Days'[print_0]) < 0, Down, IF(MAX('IM WOW% AOV-Last 7 Days'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: InstaMart\3-Last 7 Days
		lineageTag: ba485894-dabd-494c-b370-d8d9053da252

	measure 'Arrow AOV Color IM-T' = ```
			
			IF(
			                MAX('IM WOW% AOV-Today'[print_0]) > 0, 
			                "limegreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: InstaMart\1-Today
		lineageTag: 98429202-483b-45d5-9575-7ce0e806dc74

	measure 'Arrow WOW% AOV IM -T' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('IM WOW% AOV-Today'[print_0]) < 0, Down, IF(MAX('IM WOW% AOV-Today'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: InstaMart\1-Today
		lineageTag: e4518cfe-7b05-4319-9ced-ca5a59e64bb5

	measure 'Arrow AOV Color IM - Y' = ```
			
			IF(
			                MAX('IM WOW% AOV-Yesterday'[print_0]) > 0, 
			                "limegreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: InstaMart\2-Yesterday
		lineageTag: 6fd3799a-8ec2-42cc-a135-870756849b45

	measure 'Arrow WOW% AOV IM- Y' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('IM WOW% AOV-Yesterday'[print_0]) < 0, Down, IF(MAX('IM WOW% AOV-Yesterday'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: InstaMart\2-Yesterday
		lineageTag: dc62d210-c637-4884-a1f3-f5be4502fe44

	measure 'Arrow Cancelled Color IM -L4W' = ```
			
			    
			                IF(
			                MAX('IM WOW% Cancelled Orders-Last 4 Weeks'[print_0]) > 0, 
			                "tomato",  // If the value is positive, return red
			                "limeGreen"  // If the value is negative, return green
			               )
			
			```
		displayFolder: InstaMart\4-Last 4 Weeks
		lineageTag: 8a5abfd9-da38-4378-8ed2-2c7e455c4783

	measure 'Arrow WOW% Cancelled IM -L4W' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('IM WOW% Cancelled Orders-Last 4 Weeks'[print_0]) < 0, Down, IF(MAX('IM WOW% Cancelled Orders-Last 4 Weeks'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: InstaMart\4-Last 4 Weeks
		lineageTag: c4df6fcd-966f-4ac1-af3a-88733e560eef

	measure 'Arrow Cancelled Color IM -T' = ```
			
			    
			                IF(
			                MAX('IM WOW% Cancelled- Today'[print_0]) > 0, 
			                "tomato",  // If the value is positive, return red
			                "limegreen"  // If the value is negative, return green
			               )
			
			```
		displayFolder: InstaMart\1-Today
		lineageTag: a45ff973-350b-4443-a3ad-42086be76a36

	measure 'IM WOW% cancelled- T' = ```
			
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR Down = UNICHAR(9660)  // Down
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('IM WOW% Cancelled- Today'[print_0]) < 0, Down, IF(MAX('IM WOW% Cancelled- Today'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: InstaMart\1-Today
		lineageTag: fb436994-0c2c-4774-a2da-221ad8003fdd

	measure 'Arrow Cancelled Color IM -Y' = ```
			
			    
			                IF(
			                MAX('IM WOW% Cancelled- Yesterday'[print_0]) > 0, 
			                "Red",  // If the value is positive, return red
			                "Green"  // If the value is negative, return green
			               )
			
			```
		displayFolder: InstaMart\2-Yesterday
		lineageTag: e9dff8a1-a652-4623-8888-68036b04c24e

	measure 'IM WOW% cancelled- Y' = ```
			
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR Down = UNICHAR(9660)  // Down
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('IM WOW% Cancelled- Yesterday'[print_0]) < 0, Down, IF(MAX('IM WOW% Cancelled- Yesterday'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: InstaMart\2-Yesterday
		lineageTag: 48df114c-5a38-4c52-bbeb-6283a1b633e1

	measure 'Arrow Cancelled Color IM -L7D' = ```
			
			    
			                IF(
			                MAX('IM WOW% Cancelled-Last 7 Days'[print_0]) > 0, 
			                "tomato",  // If the value is positive, return red
			                "limeGreen"  // If the value is negative, return green
			               )
			
			```
		displayFolder: InstaMart\3-Last 7 Days
		lineageTag: cfcbaa11-6f16-45cc-99c0-ec54bc7e2418

	measure 'Arrow WOW% Cancelled IM -L7D' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('IM WOW% Cancelled-Last 7 Days'[print_0]) < 0, Down, IF(MAX('IM WOW% Cancelled-Last 7 Days'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: InstaMart\3-Last 7 Days
		lineageTag: efe3f42f-fddc-42d9-b2d2-581886c0233e

	measure 'Arrow Order Color IM L7D' = ```
			
			IF(
			                MAX('IM WOW% Completed Order-Last 7 Days'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: InstaMart\3-Last 7 Days
		lineageTag: 4fa6220f-2528-495e-94be-6f282ce6eecb

	measure 'Arrow WOW% Order IM L7D' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('IM WOW% Completed Order-Last 7 Days'[print_0]) < 0, Down, IF(MAX('IM WOW% Completed Order-Last 7 Days'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: InstaMart\3-Last 7 Days
		lineageTag: ecb0cff5-520a-4f5b-8120-b9fb72a8d54d

	measure 'Arrow Order Color IM' = ```
			
			IF(
			                MAX('IM WOW% Completed Order-Today'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: InstaMart\1-Today
		lineageTag: 7a7729ac-0b21-4d57-806a-ac1aa1f3129f

	measure 'Arrow WOW% Order IM' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('IM WOW% Completed Order-Today'[print_0]) < 0, Down, IF(MAX('IM WOW% Completed Order-Today'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: InstaMart\1-Today
		lineageTag: b212c764-3730-424e-9a8e-de94f8e912dd

	measure 'Arrow Order Color IM - Y' = ```
			
			IF(
			                MAX('IM WOW% Completed Order-Yesterday'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: InstaMart\2-Yesterday
		lineageTag: 4c094fef-3595-4b48-a3f3-d6313128ee46

	measure 'Arrow WOW% Order IM- Y' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('IM WOW% Completed Order-Yesterday'[print_0]) < 0, Down, IF(MAX('IM WOW% Completed Order-Yesterday'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: InstaMart\2-Yesterday
		lineageTag: 24a5d6be-3f46-4d0c-8d0c-2912dc47bd56

	measure 'Arrow GMV Color IM-L7D' = ```
			
			IF(
			                MAX('IM WOW% GMV- Last 7 Days'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: InstaMart\3-Last 7 Days
		lineageTag: b6d99a3c-72d7-45de-9808-484a84040141

	measure 'Arrow WOW% GMV IM -L4W' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('IM WOW% GMV-Last 4 Weeks'[print_0]) < 0, Down, IF(MAX('IM WOW% GMV-Last 4 Weeks'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: InstaMart\4-Last 4 Weeks
		lineageTag: c55193d3-cb8c-421b-b759-110cd5d7e40f

	measure 'Arrow WOW% GMV IM -L7D' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('IM WOW% GMV- Last 7 Days'[print_0]) < 0, Down, IF(MAX('IM WOW% GMV- Last 7 Days'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: InstaMart\3-Last 7 Days
		lineageTag: 17b16394-32c2-4a0e-82b7-aeb00b14f6dd

	measure 'Arrow GMV Color IM-L4W' = ```
			
			IF(
			                MAX('IM WOW% GMV-Last 4 Weeks'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: InstaMart\4-Last 4 Weeks
		lineageTag: 863457da-b38d-47b6-bbf4-f12ed3ae85cb

	measure 'Arrow GMV Color IM-T' = ```
			
			IF(
			                MAX('IM WOW% GMV-Today'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: InstaMart\1-Today
		lineageTag: ddf6f58d-8f8e-4331-ba36-f178fd30e601

	measure 'Arrow WOW% GMV IM -T' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('IM WOW% GMV-Today'[print_0]) < 0, Down, IF(MAX('IM WOW% GMV-Today'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: InstaMart\1-Today
		lineageTag: 08bd850b-93c3-48e6-bdb1-f847d39b2dea

	measure 'Arrow GMV Color IM - Y' = ```
			
			IF(
			                MAX('IM WOW% GMV-Yesterday'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: InstaMart\2-Yesterday
		lineageTag: 15d6df6d-d82e-4a3d-bf9a-08dfa55cd9df

	measure 'Arrow WOW% GMV IM- Y' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('IM WOW% GMV-Yesterday'[print_0]) < 0, Down, IF(MAX('IM WOW% GMV-Yesterday'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: InstaMart\2-Yesterday
		lineageTag: 58df5e92-e62f-4402-94fe-6bb24dff4e66

	measure 'Arrow Order Color IM L4W' = ```
			
			IF(
			                MAX('IM WOW% Orders-Last 4 Weeks'[print_0]) > 0, 
			                "limeGreen",  // If the value is positive, return green
			                "tomato"  // If the value is negative, return red
			               )
			
			
			```
		displayFolder: InstaMart\4-Last 4 Weeks
		lineageTag: 96a4a339-aa28-4cc1-8b6e-0816541ab651

	measure 'Arrow WOW% Order IM L4W' = ```
			
			    VAR Down = UNICHAR(9660) //Red down arrow
			    VAR Up = UNICHAR(9650)    // Up Arrow
			    VAR line = UNICHAR(8211)  // - for no changevalue
			    RETURN
			       IF(MAX('IM WOW% Orders-Last 4 Weeks'[print_0]) < 0, Down, IF(MAX('IM WOW% Orders-Last 4 Weeks'[print_0])> 0, Up, line)
			       )
			```
		displayFolder: InstaMart\4-Last 4 Weeks
		lineageTag: b678d91e-b2eb-4f47-af88-d4be9f4ee8e8

	measure 'AOV 4 Weeks' =
			
			var totalgmv = SUMX('Food AOV Count Decomposition Tree- Last 4 Weeks', 'Food AOV Count Decomposition Tree- Last 4 Weeks'[GroupAvgGmv] * 'Food AOV Count Decomposition Tree- Last 4 Weeks'[GroupCount])
			var totalcount = SUM('Food AOV Count Decomposition Tree- Last 4 Weeks'[GroupCount])
			RETURN
			DIVIDE(totalgmv, totalcount, 0)
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: e9c24bec-ec74-43c1-b1eb-fb0da7f42aab

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CDC 4 Weeks' =
			
			var totalcdc = SUMX('Food CDC% Decomposition Tree- Last 4 Weeks', 'Food CDC% Decomposition Tree- Last 4 Weeks'[GroupCDC] * 'Food CDC% Decomposition Tree- Last 4 Weeks'[GroupCDC])
			var totalcount = SUM('Food CDC% Decomposition Tree- Last 4 Weeks'[GroupCount])
			RETURN
			DIVIDE(totalcdc, totalcount, 0)
		displayFolder: Food\4-Last 4 Weeks
		lineageTag: d678e656-492c-428b-973e-ebccf2939d75

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Value
		formatString: 0
		lineageTag: 095611bb-4b98-453c-bd14-6f6c2bcd3851
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition 'ALL Measures' = calculated
		mode: import
		source = {BLANK()}

	annotation PBI_Id = 34fce00303d243da8f63763ed2938554

