table 'IM Orders Count Last 7 Days Line'
	lineageTag: 439c8c4e-2700-47ee-a8ef-23ebce43c6e3

	column COUNT_id
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 3f613ae8-4ac3-4496-bc5d-b39a015c82f4
		summarizeBy: sum
		sourceColumn: COUNT_id

		annotation SummarizationSetBy = Automatic

	column created_at_ist
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 78fda9a4-05f3-4f2d-954d-16a6a580e3f8
		summarizeBy: none
		sourceColumn: created_at_ist

		variation Variation
			isDefault
			relationship: 5a2dfb08-4c9d-43f3-836d-a06bff8ebd25
			defaultHierarchy: LocalDateTable_a0bb5996-13bf-4f97-802b-2545477b1a21.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column time_period
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: a6ab3ec5-12af-4dbd-a878-08a1620404b0
		summarizeBy: none
		sourceColumn: time_period

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 54ac486d-d1ae-41fc-8cb9-2b35bbba68cb
		summarizeBy: none
		sourceColumn: Day Name
		sortByColumn: created_at_ist

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'IM Orders Count Last 7 Days Line' = m
		mode: import
		queryGroup: 'IM\IM-Last 7 Days\IM-Sales\IM-Orders'
		source = ```
				let
				 // Get current date and time in UTC
				    TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				    // Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				    TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				    // Get today's date in IST (removes the time part)
				
				    TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				    TodayDate = DateTime.Date(TodaysDateTime),
				
				    // Get the date 7 days ago in IST
				    Last7Days = TodayDate - #duration(7, 0, 0, 0),
				
				    // Last 7 days current week to 12:00 AM IST
				    StartOfLast7Days = DateTime.FromText(Date.ToText(Last7Days) & " 00:00:00"),
				    StartOfLast7DaysFormatted = DateTime.ToText(StartOfLast7Days, "yyyy-MM-dd HH:mm:ss"),
				    CurrentDate = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				    EndofCurrentDateFormatted = DateTime.ToText(CurrentDate, "yyyy-MM-dd HH:mm:ss"),
				
				    // Last 7 days previous week to 12:00 AM IST
				    LastWeekStartDateTime = StartOfLast7Days - #duration(7, 0, 0, 0),
				    StartOfLastWeek = DateTime.FromText(Date.ToText(DateTime.Date(LastWeekStartDateTime)) & " 00:00:00"),
				    StartOfLastWeekFormatted = DateTime.ToText(StartOfLastWeek, "yyyy-MM-dd HH:mm:ss"),
				    EndofLastWeekFormatted = StartOfLast7DaysFormatted,
				    // Reference the Table Name parameter dynamically
				    TableName = IMTableName,
				
				    // Format the query with dynamic start and end times
				
				   Query = "let current_week = " & TableName & " 
				| where created_at_ist >= datetime('" & StartOfLast7DaysFormatted & "')
				| where created_at_ist < datetime('" & EndofCurrentDateFormatted & "')
				| where dp_order_type == 'INSTAMART' and (status == 'DELIVERY_DELIVERED' or status == 'COMPLETED') 
				and (order_level != 'ORDER_LEVEL_LEAF' or isempty(order_level)) 
				| summarize COUNT_id = count() by bin(created_at_ist, 1d)
				| extend time_period='Daily Trend'
				| project COUNT_id, created_at_ist, time_period;
				let last_week = " & TableName & " 
				| where created_at_ist >= datetime('" & StartOfLastWeekFormatted & "')
				| where created_at_ist < datetime('" & EndofLastWeekFormatted & "')
				| where dp_order_type == 'INSTAMART' and (status == 'DELIVERY_DELIVERED' or status == 'COMPLETED') 
				    and (order_level != 'ORDER_LEVEL_LEAF' or isempty(order_level))
				| extend created_at_ist = datetime_add('hour', 168, created_at_ist) 
				| summarize COUNT_id = count() by bin(created_at_ist, 1d)
				| extend time_period='1 Week Ago'
				| project COUNT_id, created_at_ist, time_period;
				current_week
				| union last_week",
				    // Get data from Azure Data Explorer with the dynamic query
				    Source = AzureDataExplorer.Contents(Cluster,DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"created_at_ist", type datetime}}),
				       #"Inserted Day Name" = Table.AddColumn(#"Changed Type", "Day Name", each Date.DayOfWeekName([created_at_ist]), type text),
				    #"Extracted First Characters" = Table.TransformColumns(#"Inserted Day Name", {{"Day Name", each Text.Start(_, 3), type text}})
				in
				    #"Extracted First Characters"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

