table 'Food GMV (Last 4 Weeks line)'
	lineageTag: 974e8dd6-35c6-40f3-a510-c0e516d358e1

	column COUNT_id
		dataType: double
		lineageTag: 64acd5be-3ee3-46a5-8b43-7ba28153dc87
		summarizeBy: sum
		sourceColumn: COUNT_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column created_on_ist
		dataType: dateTime
		formatString: General Date
		lineageTag: a5907ded-983f-401e-ae93-24f39b79f6ba
		summarizeBy: none
		sourceColumn: created_on_ist

		variation Variation
			isDefault
			relationship: 1bb0eb2f-1676-4ad4-81e3-8f04e036b310
			defaultHierarchy: LocalDateTable_51d38962-e6ee-4d21-b992-c255a13eff5c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column period
		dataType: string
		lineageTag: 3cbb4ad9-0051-4788-a4b2-dfba5f6c002d
		summarizeBy: none
		sourceColumn: period

		annotation SummarizationSetBy = Automatic

	partition 'Food GMV (Last 4 Weeks line)' = m
		mode: import
		queryGroup: 'Food\Food- Last 4 weeks\Food- Sales\Food-GMV'
		source = ```
				let   
				// Get current date and time in UTC
				TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				// Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				// Get today's date in IST (removes the time part)
				
				TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				TodayDate = DateTime.Date(TodaysDateTime),
				
				// Get the date 28 days ago in IST
				Last28Days = TodayDate - #duration(28, 0, 0, 0),
				
				// Last 28 days current week to 12:00 AM IST
				StartOfLast28Days = DateTime.FromText(Date.ToText(Last28Days) & " 00:00:00"),
				StartOfLast28DaysFormatted = DateTime.ToText(StartOfLast28Days, "yyyy-MM-dd HH:mm:ss"),
				CurrentDate = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				EndofCurrentDateFormatted = DateTime.ToText(CurrentDate, "yyyy-MM-dd HH:mm:ss"),
				
				// Last 28 days previous week to 12:00 AM IST
				Last4WeekStartDateTime = StartOfLast28Days - #duration(28, 0, 0, 0),
				StartOfLast4Week = DateTime.FromText(Date.ToText(DateTime.Date(Last4WeekStartDateTime)) & " 00:00:00"),
				StartOfLast4WeekFormatted = DateTime.ToText(StartOfLast4Week, "yyyy-MM-dd HH:mm:ss"),
				EndofLast4WeekFormatted = StartOfLast28DaysFormatted,
				
				    TableName = FoodTableName,
				
				    Query = "let currentperiod = " & TableName & " 
				| where created_on_ist >= datetime('"& StartOfLast28DaysFormatted &"') 
				| where created_on_ist < datetime('"& EndofCurrentDateFormatted &"') 
				| where order_status == 'completed' and order_type != 'SUBSCRIPTION' 
				| summarize COUNT_id = round(sum(gmv_total), 2) by bin(created_on_ist, 1d)
				| extend period='Daily Trend'
				| project COUNT_id, created_on_ist, period;
				let perviousperiod = " & TableName & " 
				| where created_on_ist >= datetime('"& StartOfLast4WeekFormatted &"') 
				| where created_on_ist < datetime('"& EndofLast4WeekFormatted &"') 
				| where order_status == 'completed' and order_type != 'SUBSCRIPTION'
				| extend created_on_ist = datetime_add('hour', 672, created_on_ist)
				| summarize COUNT_id = round(sum(gmv_total), 2) by bin(created_on_ist, 1d)
				| extend period='4 Weeks Ago'
				| project COUNT_id, created_on_ist, period;
				currentperiod
				| union perviousperiod",
				    // Get data from Azure Data Explorer with the dynamic query
				    Source = AzureDataExplorer.Contents(Cluster,DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"created_on_ist", type datetime}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

