table 'Food RDC% Line Last 7 Days'
	lineageTag: a3bfd120-ccba-44f2-824a-ac5801fe6455

	column rdc
		dataType: double
		sourceProviderType: double
		lineageTag: c2aef5da-45f5-4432-88e6-d0de5f84d107
		summarizeBy: sum
		sourceColumn: rdc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column created_on_ist
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 8c2d5f7e-0d0d-4b4e-9605-ab0032910753
		summarizeBy: none
		sourceColumn: created_on_ist

		variation Variation
			isDefault
			relationship: 97c7f234-5388-4821-8159-c2a425659b9d
			defaultHierarchy: LocalDateTable_2d6bb791-74a2-4510-9c56-62a414284e30.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column time_period
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 2d703c04-0774-4c40-a23b-d33928cf5e1c
		summarizeBy: none
		sourceColumn: time_period

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 12b5fb2e-9618-4ca3-b3df-209e4bfacbde
		summarizeBy: none
		sourceColumn: Day Name
		sortByColumn: created_on_ist

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Food RDC% Line Last 7 Days' = m
		mode: import
		queryGroup: 'Food\Food- Last 7 Days\Food-Cancelation\Food-RDC'
		source = ```
				let   
				    // Get current date and time in UTC
				TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				// Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				// Get today's date in IST (removes the time part)
				
				TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				TodayDate = DateTime.Date(TodaysDateTime),
				
				// Get the date 7 days ago in IST
				Last7Days = TodayDate - #duration(7, 0, 0, 0),
				
				// Last 7 days current week to 12:00 AM IST
				StartOfLast7Days = DateTime.FromText(Date.ToText(Last7Days) & " 00:00:00"),
				StartOfLast7DaysFormatted = DateTime.ToText(StartOfLast7Days, "yyyy-MM-dd HH:mm:ss"),
				CurrentDate = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				EndofCurrentDateFormatted = DateTime.ToText(CurrentDate, "yyyy-MM-dd HH:mm:ss"),
				
				// Last 7 days previous week to 12:00 AM IST
				LastWeekStartDateTime = StartOfLast7Days - #duration(7, 0, 0, 0),
				StartOfLastWeek = DateTime.FromText(Date.ToText(DateTime.Date(LastWeekStartDateTime)) & " 00:00:00"),
				StartOfLastWeekFormatted = DateTime.ToText(StartOfLastWeek, "yyyy-MM-dd HH:mm:ss"),
				EndofLastWeekFormatted = StartOfLast7DaysFormatted,
				
				    TableName = FoodTableName,
				
				    Query = "let currentweek = " & TableName & " 
				| where created_on_ist >= datetime('"& StartOfLast7DaysFormatted &"') 
				| where created_on_ist < datetime('"& EndofCurrentDateFormatted &"') 
				| extend cancelled = iff(order_status == 'cancelled' and order_type != 'SUBSCRIPTION' and canceled_reason == '2', 1.0, 0.0) 
				| extend all_orders = iff(((order_status == 'completed' or order_status == 'cancelled' or order_status == 'processing') and order_type != 'SUBSCRIPTION'), 1.0, 0.0) 
				| summarize rdc = sum(cancelled)/sum(all_orders)*100 by bin(created_on_ist, 1d) 
				| extend time_period='Daily Trend'
				| project rdc, created_on_ist, time_period;
				let last_week = " & TableName & " 
				| where created_on_ist >= datetime('"& StartOfLastWeekFormatted &"') 
				| where created_on_ist < datetime('"& EndofLastWeekFormatted &"')  
				| extend cancelled = iff(order_status == 'cancelled' and order_type != 'SUBSCRIPTION' and canceled_reason == '2', 1.0, 0.0) 
				| extend all_orders = iff(((order_status == 'completed' or order_status == 'cancelled' or order_status == 'processing') and order_type != 'SUBSCRIPTION'), 1.0, 0.0) 
				| extend created_on_ist = datetime_add('hour', 168, created_on_ist)
				| summarize rdc = sum(cancelled)/sum(all_orders)*100 by bin(created_on_ist, 1d) 
				| extend time_period='1 Week Ago'
				| project rdc, created_on_ist, time_period;
				currentweek
				| union last_week",
				 
				    // Get data from Azure Data Explorer with the dynamic query
				   Source = AzureDataExplorer.Contents(Cluster,DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"created_on_ist", type datetime}}),
				    #"Inserted Day Name" = Table.AddColumn(#"Changed Type", "Day Name", each Date.DayOfWeekName([created_on_ist]), type text),
				    #"Extracted First Characters" = Table.TransformColumns(#"Inserted Day Name", {{"Day Name", each Text.Start(_, 3), type text}})
				in
				    #"Extracted First Characters"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

