table 'Food AOV Last 7 Days Line'
	lineageTag: 9fc6fdec-028e-4150-b261-8d908d937a2e

	column COUNT_id
		dataType: double
		sourceProviderType: double
		lineageTag: 445668e4-06d6-4c86-8479-e369789a9bbd
		summarizeBy: sum
		sourceColumn: COUNT_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column created_on_ist
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 3a4cebe6-7555-4dc4-95c3-fb552d78c4fa
		summarizeBy: none
		sourceColumn: created_on_ist

		variation Variation
			isDefault
			relationship: e9f69a2e-f6a9-4609-a9a7-18bdf6fd7270
			defaultHierarchy: LocalDateTable_b797cdd1-07b5-4ca9-a990-1a39f9c5ab84.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column time_period
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 3099f581-a97c-4dfe-a5b6-235a1040a340
		summarizeBy: none
		sourceColumn: time_period

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 896b4444-bb20-4f7a-ae0a-f58ddd23e79b
		summarizeBy: none
		sourceColumn: Day Name
		sortByColumn: created_on_ist

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Food AOV Last 7 Days Line' = m
		mode: import
		queryGroup: 'Food\Food- Last 7 Days\Food- Sales\Food-AOV'
		source = ```
				let 
				// Get current date and time in UTC
				TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				// Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				// Get today's date in IST (removes the time part)
				
				TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				TodayDate = DateTime.Date(TodaysDateTime),
				
				// Get the date 7 days ago in IST
				Last7Days = TodayDate - #duration(7, 0, 0, 0),
				
				// Last 7 days current week to 12:00 AM IST
				StartOfLast7Days = DateTime.FromText(Date.ToText(Last7Days) & " 00:00:00"),
				StartOfLast7DaysFormatted = DateTime.ToText(StartOfLast7Days, "yyyy-MM-dd HH:mm:ss"),
				CurrentDate = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				EndofCurrentDateFormatted = DateTime.ToText(CurrentDate, "yyyy-MM-dd HH:mm:ss"),
				
				// Last 7 days previous week to 12:00 AM IST
				LastWeekStartDateTime = StartOfLast7Days - #duration(7, 0, 0, 0),
				StartOfLastWeek = DateTime.FromText(Date.ToText(DateTime.Date(LastWeekStartDateTime)) & " 00:00:00"),
				StartOfLastWeekFormatted = DateTime.ToText(StartOfLastWeek, "yyyy-MM-dd HH:mm:ss"),
				EndofLastWeekFormatted = StartOfLast7DaysFormatted,
				
				    // // Reference the Table Name parameter dynamically
				    TableName = FoodTableName,
				
				    // // Format the query with dynamic start and end times for yesterday in IST
				 
				    Query = "let currentweek = " & TableName & " 
				    | where created_on_ist >= datetime('"& StartOfLast7DaysFormatted & "') 
				    | where created_on_ist < datetime('"& EndofCurrentDateFormatted &"') 
				    | where order_status == 'completed' and order_type != 'SUBSCRIPTION' 
				    | summarize COUNT_id = round(avg(gmv_total), 2) by bin(created_on_ist, 1d)
				    | extend time_period='Daily Trend'
				    | project COUNT_id, created_on_ist, time_period;
				    let last_week = " & TableName & " 
				    | where created_on_ist >= datetime('"& StartOfLastWeekFormatted & "')
				    | where created_on_ist < datetime('"& EndofLastWeekFormatted &"') 
				    | where order_status == 'completed' and order_type != 'SUBSCRIPTION'
				    | extend created_on_ist = datetime_add('hour', 168, created_on_ist) 
				    | summarize COUNT_id = round(avg(gmv_total), 2) by bin(created_on_ist, 1d)
				    | extend time_period='1 Week Ago'
				    | project COUNT_id, created_on_ist, time_period;
				    currentweek
				    | union last_week",
				
				        // // Get data from Azure Data Explorer with the dynamic query
				    Source = AzureDataExplorer.Contents(Cluster,DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"created_on_ist", type datetime}}),
				    #"Inserted Day Name" = Table.AddColumn(#"Changed Type", "Day Name", each Date.DayOfWeekName([created_on_ist]), type text),
				    #"Extracted First Characters" = Table.TransformColumns(#"Inserted Day Name", {{"Day Name", each Text.Start(_, 3), type text}})
				in
				    #"Extracted First Characters"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

