table 'Food SDC% line Last 7 Days'
	lineageTag: 9d807ff5-d24c-4277-a974-2300e9791722

	column sdc
		dataType: double
		sourceProviderType: double
		lineageTag: fbfd8d19-2778-4f69-968b-5e122a2bfd12
		summarizeBy: sum
		sourceColumn: sdc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column created_on_ist
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 0529f139-82d0-444a-970d-fac499fc0443
		summarizeBy: none
		sourceColumn: created_on_ist

		variation Variation
			isDefault
			relationship: 25e8d12e-49f4-44e7-a742-1072ec565838
			defaultHierarchy: LocalDateTable_1207a018-f088-4107-88a2-4e67f9873e49.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column time_period
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 0b123c90-00ee-4e5f-b7c8-b52ba7e805ff
		summarizeBy: none
		sourceColumn: time_period

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 54264bdf-119b-4cdb-85ff-c512dff1c60d
		summarizeBy: none
		sourceColumn: Day Name
		sortByColumn: created_on_ist

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Food SDC% line Last 7 Days' = m
		mode: import
		queryGroup: 'Food\Food- Last 7 Days\Food-Cancelation\Food-SDC'
		source = ```
				let
				// Get current date and time in UTC
				TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				// Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				// Get today's date in IST (removes the time part)
				
				TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				TodayDate = DateTime.Date(TodaysDateTime),
				
				// Get the date 7 days ago in IST
				Last7Days = TodayDate - #duration(7, 0, 0, 0),
				
				// Last 7 days current week to 12:00 AM IST
				StartOfLast7Days = DateTime.FromText(Date.ToText(Last7Days) & " 00:00:00"),
				StartOfLast7DaysFormatted = DateTime.ToText(StartOfLast7Days, "yyyy-MM-dd HH:mm:ss"),
				CurrentDate = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				EndofCurrentDateFormatted = DateTime.ToText(CurrentDate, "yyyy-MM-dd HH:mm:ss"),
				
				// Last 7 days previous week to 12:00 AM IST
				LastWeekStartDateTime = StartOfLast7Days - #duration(7, 0, 0, 0),
				StartOfLastWeek = DateTime.FromText(Date.ToText(DateTime.Date(LastWeekStartDateTime)) & " 00:00:00"),
				StartOfLastWeekFormatted = DateTime.ToText(StartOfLastWeek, "yyyy-MM-dd HH:mm:ss"),
				EndofLastWeekFormatted = StartOfLast7DaysFormatted,
				
				    // Reference the Table Name parameter dynamically
				    TableName = FoodTableName,
				
				//Query for same timeframe
				 Query ="let currentweek = " & TableName & " 
				| where created_on_ist >= datetime('"& StartOfLast7DaysFormatted &"') 
				| where created_on_ist < datetime('"& EndofCurrentDateFormatted &"') 
				| extend cancelled = iff(order_status == 'cancelled' and order_type != 'SUBSCRIPTION' and canceled_reason == '1', 1.0, 0.0) 
				| extend all_orders = iff(((order_status == 'completed' or order_status == 'cancelled' or order_status == 'processing') and order_type != 'SUBSCRIPTION'), 1.0, 0.0) 
				| summarize sdc = round(sum(cancelled)/sum(all_orders)*100,2) by bin(created_on_ist, 1d) 
				| extend time_period='Daily Trend'
				| project sdc, created_on_ist, time_period;
				let last_week  = " & TableName & " 
				| where created_on_ist >= datetime('"& StartOfLastWeekFormatted &"') 
				| where created_on_ist < datetime('"& EndofLastWeekFormatted &"') 
				| extend cancelled = iff(order_status == 'cancelled' and order_type != 'SUBSCRIPTION' and canceled_reason == '1', 1.0, 0.0) 
				| extend all_orders = iff(((order_status == 'completed' or order_status == 'cancelled' or order_status == 'processing') and order_type != 'SUBSCRIPTION'), 1.0, 0.0) 
				| extend created_on_ist = datetime_add('hour', 168, created_on_ist)
				| summarize sdc = round(sum(cancelled)/sum(all_orders)*100,2) by bin(created_on_ist, 1d) 
				| extend time_period='1 Week Ago'
				| project sdc, created_on_ist, time_period;
				currentweek
				| union last_week",
				
				 // Get data from Azure Data Explorer with the dynamic query
				    Source = AzureDataExplorer.Contents(Cluster,DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"created_on_ist", type datetime}}),
				    #"Inserted Day Name" = Table.AddColumn(#"Changed Type", "Day Name", each Date.DayOfWeekName([created_on_ist]), type text),
				    #"Extracted First Characters" = Table.TransformColumns(#"Inserted Day Name", {{"Day Name", each Text.Start(_, 3), type text}})
				in
				    #"Extracted First Characters"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

