table 'Food Cancelled Orders Line Last 4 Weeks'
	lineageTag: c923b648-2e9c-4d4e-b06b-97cb280380ac

	column COUNT_id
		dataType: int64
		formatString: 0
		lineageTag: 57418de4-0478-42dc-91ff-68cc580afc61
		summarizeBy: sum
		sourceColumn: COUNT_id

		annotation SummarizationSetBy = Automatic

	column created_on_ist
		dataType: dateTime
		formatString: General Date
		lineageTag: b10eb357-6e8e-4a71-ba6c-45c6d48c16b2
		summarizeBy: none
		sourceColumn: created_on_ist

		variation Variation
			isDefault
			relationship: 562d61a0-ad99-4500-91f4-8ddacb8c182c
			defaultHierarchy: LocalDateTable_43a5ae13-92ff-4905-a660-77b3889f9c38.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column period
		dataType: string
		lineageTag: f3ac31fa-aa13-4f36-8acd-7a504bcdfdfa
		summarizeBy: none
		sourceColumn: period

		annotation SummarizationSetBy = Automatic

	partition 'Food Cancelled Orders Line Last 4 Weeks' = m
		mode: import
		queryGroup: 'Food\Food- Last 4 weeks\Food-Cancellation\Food-Cancelled Orders'
		source = ```
				let
				   // Get current date and time in UTC
				TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				// Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				// Get today's date in IST (removes the time part)
				
				TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				TodayDate = DateTime.Date(TodaysDateTime),
				
				// Get the date 28 days ago in IST
				Last28Days = TodayDate - #duration(28, 0, 0, 0),
				
				// Last 28 days current week to 12:00 AM IST
				StartOfLast28Days = DateTime.FromText(Date.ToText(Last28Days) & " 00:00:00"),
				StartOfLast28DaysFormatted = DateTime.ToText(StartOfLast28Days, "yyyy-MM-dd HH:mm:ss"),
				CurrentDate = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				EndofCurrentDateFormatted = DateTime.ToText(CurrentDate, "yyyy-MM-dd HH:mm:ss"),
				
				// Last 28 days previous week to 12:00 AM IST
				Last4WeekStartDateTime = StartOfLast28Days - #duration(28, 0, 0, 0),
				StartOfLast4Week = DateTime.FromText(Date.ToText(DateTime.Date(Last4WeekStartDateTime)) & " 00:00:00"),
				StartOfLast4WeekFormatted = DateTime.ToText(StartOfLast4Week, "yyyy-MM-dd HH:mm:ss"),
				EndofLast4WeekFormatted = StartOfLast28DaysFormatted,
				
				    TableName = FoodTableName,
				
				    Query = "let currentperiod = " & TableName & " 
				| where created_on_ist >= datetime('"& StartOfLast28DaysFormatted &"') 
				| where created_on_ist < datetime('"& EndofCurrentDateFormatted &"') 
				| where order_status == 'cancelled' 
				| summarize COUNT_id = count() by bin(created_on_ist, 1d)
				| extend period='Daily Trend'
				| project COUNT_id, created_on_ist, period;
				let previousperiod = " & TableName & "
				| where created_on_ist >= datetime('"& StartOfLast4WeekFormatted &"') 
				| where created_on_ist < datetime('" & EndofLast4WeekFormatted &" ') 
				| where order_status == 'cancelled'
				| extend created_on_ist = datetime_add('hour', 672, created_on_ist)
				| summarize COUNT_id = count() by bin(created_on_ist, 1d)
				| extend period='4 Weeks Ago'
				| project COUNT_id, created_on_ist, period;
				currentperiod
				| union previousperiod",
				    // Get data from Azure Data Explorer with the dynamic query
				    Source = AzureDataExplorer.Contents(Cluster,DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"created_on_ist", type datetime}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

