table 'Food Orders Count Last 7 Weeks Line'
	lineageTag: 4a4f9d33-a42c-4d8a-b46c-dd666d8762ec

	column COUNT_id
		dataType: int64
		formatString: 0
		lineageTag: 379d34f9-3ba6-4c01-b712-b1536bdc9aaa
		summarizeBy: sum
		sourceColumn: COUNT_id

		annotation SummarizationSetBy = Automatic

	column created_on_ist
		dataType: dateTime
		formatString: General Date
		lineageTag: 33e1c5c8-6ca7-49bc-ac25-8ae5722ec8b8
		summarizeBy: none
		sourceColumn: created_on_ist

		variation Variation
			isDefault
			relationship: a97d231c-3c89-46c0-8566-42e964a7e601
			defaultHierarchy: LocalDateTable_ecb05ab7-2ba6-4cbe-a3ac-cd0c1292e6e4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column period
		dataType: string
		lineageTag: f86556c6-fa67-470b-9f13-37365286ebef
		summarizeBy: none
		sourceColumn: period

		annotation SummarizationSetBy = Automatic

	partition 'Food Orders Count Last 7 Weeks Line' = m
		mode: import
		queryGroup: 'Food\Food- Last 4 weeks\Food- Sales\Food-Orders'
		source = ```
				let
				    // Get current date and time in UTC
				TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				// Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				// Get today's date in IST (removes the time part)
				
				TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				TodayDate = DateTime.Date(TodaysDateTime),
				
				// Get the date 28 days ago in IST
				Last28Days = TodayDate - #duration(28, 0, 0, 0),
				
				// Last 28 days current week to 12:00 AM IST
				StartOfLast28Days = DateTime.FromText(Date.ToText(Last28Days) & " 00:00:00"),
				StartOfLast28DaysFormatted = DateTime.ToText(StartOfLast28Days, "yyyy-MM-dd HH:mm:ss"),
				CurrentDate = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				EndofCurrentDateFormatted = DateTime.ToText(CurrentDate, "yyyy-MM-dd HH:mm:ss"),
				
				// Last 28 days previous week to 12:00 AM IST
				Last4WeekStartDateTime = StartOfLast28Days - #duration(28, 0, 0, 0),
				StartOfLast4Week = DateTime.FromText(Date.ToText(DateTime.Date(Last4WeekStartDateTime)) & " 00:00:00"),
				StartOfLast4WeekFormatted = DateTime.ToText(StartOfLast4Week, "yyyy-MM-dd HH:mm:ss"),
				EndofLast4WeekFormatted = StartOfLast28DaysFormatted,
				
				    // Reference the Table Name parameter dynamically
				    TableName = FoodTableName,
				
				    // Format the query with dynamic start and end times
				
				    Query = "let currentperiod = " & TableName & " 
				| where created_on_ist >= datetime('" & StartOfLast28DaysFormatted & "')
				| where created_on_ist < datetime('" & EndofCurrentDateFormatted & "')
				| where order_status == 'completed'
				| where order_type != 'SUBSCRIPTION'
				| summarize COUNT_id = count() by bin(created_on_ist, 1d)
				| extend period='Daily Trend'
				| project COUNT_id, created_on_ist, period;
				let previousperiod = " & TableName & " 
				| where created_on_ist >= datetime('" & StartOfLast4WeekFormatted & "')
				| where created_on_ist < datetime('" & EndofLast4WeekFormatted & "')
				| where order_status == 'completed'
				| where order_type != 'SUBSCRIPTION'
				| extend created_on_ist = datetime_add('hour', 672, created_on_ist)
				| summarize COUNT_id = count() by bin(created_on_ist, 1d)
				| extend period='4 Weeks Ago'
				| project COUNT_id, created_on_ist, period;
				currentperiod
				| union previousperiod",
				    // Get data from Azure Data Explorer with the dynamic query
				    Source = AzureDataExplorer.Contents(Cluster,DB,Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"created_on_ist", type datetime}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

