table 'Food AOV Last 4 Weeks Line'
	lineageTag: 0188ec31-400a-4d4c-b322-872e49fbc454

	column COUNT_id
		dataType: double
		lineageTag: 26e9bd3e-1a04-48a8-866c-3a580fed6595
		summarizeBy: sum
		sourceColumn: COUNT_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column created_on_ist
		dataType: dateTime
		formatString: General Date
		lineageTag: ca27ea23-ea24-4ab0-920c-514bed7d2393
		summarizeBy: none
		sourceColumn: created_on_ist

		variation Variation
			isDefault
			relationship: f4e72fa8-4038-4b06-80c0-c5dc0382c0e5
			defaultHierarchy: LocalDateTable_0fef75f9-52c5-48c6-89d5-8f738b52b986.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column period
		dataType: string
		lineageTag: 78ee6fbc-a226-4e90-87e8-5a2baf4297ba
		summarizeBy: none
		sourceColumn: period

		annotation SummarizationSetBy = Automatic

	partition 'Food AOV Last 4 Weeks Line' = m
		mode: import
		queryGroup: 'Food\Food- Last 4 weeks\Food- Sales\Food-AOV'
		source = ```
				let 
				// Get current date and time in UTC
				TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				// Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				// Get today's date in IST (removes the time part)
				
				TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				TodayDate = DateTime.Date(TodaysDateTime),
				
				// Get the date 28 days ago in IST
				Last28Days = TodayDate - #duration(28, 0, 0, 0),
				
				// Last 28 days current week to 12:00 AM IST
				StartOfLast28Days = DateTime.FromText(Date.ToText(Last28Days) & " 00:00:00"),
				StartOfLast28DaysFormatted = DateTime.ToText(StartOfLast28Days, "yyyy-MM-dd HH:mm:ss"),
				CurrentDate = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				EndofCurrentDateFormatted = DateTime.ToText(CurrentDate, "yyyy-MM-dd HH:mm:ss"),
				
				// Last 28 days previous week to 12:00 AM IST
				Last4WeekStartDateTime = StartOfLast28Days - #duration(28, 0, 0, 0),
				StartOfLast4Week = DateTime.FromText(Date.ToText(DateTime.Date(Last4WeekStartDateTime)) & " 00:00:00"),
				StartOfLast4WeekFormatted = DateTime.ToText(StartOfLast4Week, "yyyy-MM-dd HH:mm:ss"),
				EndofLast4WeekFormatted = StartOfLast28DaysFormatted,
				
				    // // Reference the Table Name parameter dynamically
				    TableName = FoodTableName,
				
				    // // Format the query with dynamic start and end times for yesterday in IST
				 
				    Query = "let currentperiod = " & TableName & " 
				    | where created_on_ist >= datetime('"& StartOfLast28DaysFormatted & "') 
				    | where created_on_ist < datetime('"& EndofCurrentDateFormatted &"') 
				    | where order_status == 'completed' and order_type != 'SUBSCRIPTION' 
				    | summarize COUNT_id = round(avg(gmv_total), 2) by bin(created_on_ist, 1d)
				    | extend period='Daily Trend'
				    | project COUNT_id, created_on_ist, period;
				    let previousperiod = " & TableName & " 
				    | where created_on_ist >= datetime('"& StartOfLast4WeekFormatted & "')
				    | where created_on_ist < datetime('"& EndofLast4WeekFormatted &"') 
				    | where order_status == 'completed' and order_type != 'SUBSCRIPTION'
				    | extend created_on_ist = datetime_add('hour', 672, created_on_ist) 
				    | summarize COUNT_id = round(avg(gmv_total), 2) by bin(created_on_ist, 1d)
				    | extend period='4 Weeks Ago'
				    | project COUNT_id, created_on_ist, period;
				    currentperiod
				    | union previousperiod",
				
				        // // Get data from Azure Data Explorer with the dynamic query
				    Source = AzureDataExplorer.Contents(Cluster,DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"created_on_ist", type datetime}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

