table 'Food Transacting Users Line (Last 7 Days)'
	lineageTag: 51def4f8-70ec-487c-89b4-86f5f7ad018c

	column ftu
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: c04ebd92-ff16-4cae-8c6b-1f13c630a49c
		summarizeBy: sum
		sourceColumn: ftu

		annotation SummarizationSetBy = Automatic

	column created_on_ist
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 6830c200-447b-4f06-a46e-97a708837426
		summarizeBy: none
		sourceColumn: created_on_ist

		variation Variation
			isDefault
			relationship: 257f005b-735f-416f-8663-5ec246714f58
			defaultHierarchy: LocalDateTable_8efe377e-1e0f-44a2-a972-8c94573f54d7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column time_period
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 92cf708d-1055-4944-b1ae-3cb1520636a2
		summarizeBy: none
		sourceColumn: time_period

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 1dc6964a-4214-4dda-9de7-728f5e27b7a9
		summarizeBy: none
		sourceColumn: Day Name
		sortByColumn: created_on_ist

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Food Transacting Users Line (Last 7 Days)' = m
		mode: import
		queryGroup: 'Food\Food- Last 7 Days\Food-consumers\Food-FTU'
		source = ```
				let
				    // Get current date and time in UTC
				TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				// Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				// Get today's date in IST (removes the time part)
				
				TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				TodayDate = DateTime.Date(TodaysDateTime),
				
				// Get the date 7 days ago in IST
				Last7Days = TodayDate - #duration(7, 0, 0, 0),
				
				// Last 7 days current week to 12:00 AM IST
				StartOfLast7Days = DateTime.FromText(Date.ToText(Last7Days) & " 00:00:00"),
				StartOfLast7DaysFormatted = DateTime.ToText(StartOfLast7Days, "yyyy-MM-dd HH:mm:ss"),
				CurrentDate = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				EndofCurrentDateFormatted = DateTime.ToText(CurrentDate, "yyyy-MM-dd HH:mm:ss"),
				
				// Last 7 days previous week to 12:00 AM IST
				LastWeekStartDateTime = StartOfLast7Days - #duration(7, 0, 0, 0),
				StartOfLastWeek = DateTime.FromText(Date.ToText(DateTime.Date(LastWeekStartDateTime)) & " 00:00:00"),
				StartOfLastWeekFormatted = DateTime.ToText(StartOfLastWeek, "yyyy-MM-dd HH:mm:ss"),
				EndofLastWeekFormatted = StartOfLast7DaysFormatted,
				
				    TableName = FoodTableName,
				
				    Query = "let currentweek = " & TableName & " 
				| where created_on_ist >= datetime('"& StartOfLast7DaysFormatted &"') 
				| where created_on_ist < datetime('"& EndofCurrentDateFormatted &"') 
				| where order_status == 'completed'  and order_type != 'SUBSCRIPTION'
				| summarize ftu = count_distinct(user_id) by bin(created_on_ist, 1d)  
				| extend time_period='Daily Trend'
				| project ftu, created_on_ist, time_period;
				let last_week = " & TableName & " 
				| where created_on_ist >= datetime('"& StartOfLastWeekFormatted &"') 
				| where created_on_ist < datetime('"& EndofLastWeekFormatted &"') 
				| where order_status == 'completed'  and order_type != 'SUBSCRIPTION'
				| extend created_on_ist = datetime_add('hour', 168, created_on_ist)
				| summarize ftu = count_distinct(user_id) by bin(created_on_ist, 1d)  
				| extend time_period='1 Week Ago'
				| project ftu, created_on_ist, time_period;
				currentweek
				| union last_week",
				    // Get data from Azure Data Explorer with the dynamic query
				    Source = AzureDataExplorer.Contents(Cluster,DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"created_on_ist", type datetime}}),
				    #"Inserted Day Name" = Table.AddColumn(#"Changed Type", "Day Name", each Date.DayOfWeekName([created_on_ist]), type text),
				    #"Extracted First Characters" = Table.TransformColumns(#"Inserted Day Name", {{"Day Name", each Text.Start(_, 3), type text}})
				in
				    #"Extracted First Characters"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

