table 'Food Transacting Resturants Line (Last 4 Weeks)'
	lineageTag: a5632efd-f232-403f-9956-67cebde217c7

	column ftr
		dataType: int64
		formatString: 0
		lineageTag: 44d6cba5-6639-4eab-9d0f-f8f991e5db66
		summarizeBy: sum
		sourceColumn: ftr

		annotation SummarizationSetBy = Automatic

	column created_on_ist
		dataType: dateTime
		formatString: General Date
		lineageTag: c0203f79-86c5-48a8-8eaf-0944bfbe9453
		summarizeBy: none
		sourceColumn: created_on_ist

		variation Variation
			isDefault
			relationship: 81ee6ead-592f-4851-88ac-b4325e576560
			defaultHierarchy: LocalDateTable_7f5f0a93-dfdb-4042-9372-bda458a1cd10.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column period
		dataType: string
		lineageTag: ef90cf76-02ec-4266-8ed4-1b5dce1d4559
		summarizeBy: none
		sourceColumn: period

		annotation SummarizationSetBy = Automatic

	partition 'Food Transacting Resturants Line (Last 4 Weeks)' = m
		mode: import
		queryGroup: 'Food\Food- Last 4 weeks\Food-food supply\Food-FTR'
		source = ```
				let
				    // Get current date and time in UTC
				TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				// Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				// Get today's date in IST (removes the time part)
				
				TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				TodayDate = DateTime.Date(TodaysDateTime),
				
				// Get the date 28 days ago in IST
				Last28Days = TodayDate - #duration(28, 0, 0, 0),
				
				// Last 28 days current week to 12:00 AM IST
				StartOfLast28Days = DateTime.FromText(Date.ToText(Last28Days) & " 00:00:00"),
				StartOfLast28DaysFormatted = DateTime.ToText(StartOfLast28Days, "yyyy-MM-dd HH:mm:ss"),
				CurrentDate = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				EndofCurrentDateFormatted = DateTime.ToText(CurrentDate, "yyyy-MM-dd HH:mm:ss"),
				
				// Last 28 days previous week to 12:00 AM IST
				Last4WeekStartDateTime = StartOfLast28Days - #duration(28, 0, 0, 0),
				StartOfLast4Week = DateTime.FromText(Date.ToText(DateTime.Date(Last4WeekStartDateTime)) & " 00:00:00"),
				StartOfLast4WeekFormatted = DateTime.ToText(StartOfLast4Week, "yyyy-MM-dd HH:mm:ss"),
				EndofLast4WeekFormatted = StartOfLast28DaysFormatted,
				
				    TableName = FoodTableName,
				
				    Query = "let curentperiod = " & TableName & " 
				| where created_on_ist >= datetime('"& StartOfLast28DaysFormatted &"') 
				| where created_on_ist < datetime('"& EndofCurrentDateFormatted &"') 
				| where order_status == 'completed' 
				| where isnotempty(restaurantId)  
				| summarize ftr = count_distinct(restaurantId) by bin(created_on_ist, 1d) 
				| extend period='Daily Trend'
				| project ftr, created_on_ist, period;
				let previousperiod = " & TableName & " 
				| where created_on_ist >= datetime('"& StartOfLast4WeekFormatted &"') 
				| where created_on_ist < datetime('"& EndofLast4WeekFormatted &"') 
				| where order_status == 'completed' 
				| where isnotempty(restaurantId)
				| extend created_on_ist = datetime_add('hour', 672, created_on_ist)  
				| summarize ftr = count_distinct(restaurantId) by bin(created_on_ist, 1d) 
				| extend period='4 Weeks Ago'
				| project ftr, created_on_ist, period;
				curentperiod
				| union previousperiod",
				    // Get data from Azure Data Explorer with the dynamic query
				    Source = AzureDataExplorer.Contents(Cluster,DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"created_on_ist", type datetime}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

