table 'Food RDC% Line Last 4 Weeks'
	lineageTag: a07d0612-38ff-4a8d-bbb2-d67ec17f1125

	column rdc
		dataType: double
		lineageTag: 44fa07d8-0b0a-47af-9702-140e138ce0cc
		summarizeBy: sum
		sourceColumn: rdc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column created_on_ist
		dataType: dateTime
		formatString: General Date
		lineageTag: 6700e6b3-2fae-4408-9ac1-e1c09ae0cb93
		summarizeBy: none
		sourceColumn: created_on_ist

		variation Variation
			isDefault
			relationship: 4838d030-345f-4210-a704-8ef5e1668a86
			defaultHierarchy: LocalDateTable_2abb2819-70f2-48c6-87aa-c6d4f4e88750.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column period
		dataType: string
		lineageTag: 0babddb9-01b5-4afb-a76d-b66d7b1b9d65
		summarizeBy: none
		sourceColumn: period

		annotation SummarizationSetBy = Automatic

	partition 'Food RDC% Line Last 4 Weeks' = m
		mode: import
		queryGroup: 'Food\Food- Last 4 weeks\Food-Cancellation\Food-RDC'
		source = ```
				let   
				    // Get current date and time in UTC
				TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				// Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				// Get today's date in IST (removes the time part)
				
				TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				TodayDate = DateTime.Date(TodaysDateTime),
				
				// Get the date 28 days ago in IST
				Last28Days = TodayDate - #duration(28, 0, 0, 0),
				
				// Last 28 days current week to 12:00 AM IST
				StartOfLast28Days = DateTime.FromText(Date.ToText(Last28Days) & " 00:00:00"),
				StartOfLast28DaysFormatted = DateTime.ToText(StartOfLast28Days, "yyyy-MM-dd HH:mm:ss"),
				CurrentDate = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				EndofCurrentDateFormatted = DateTime.ToText(CurrentDate, "yyyy-MM-dd HH:mm:ss"),
				
				// Last 28 days previous week to 12:00 AM IST
				Last4WeekStartDateTime = StartOfLast28Days - #duration(28, 0, 0, 0),
				StartOfLast4Week = DateTime.FromText(Date.ToText(DateTime.Date(Last4WeekStartDateTime)) & " 00:00:00"),
				StartOfLast4WeekFormatted = DateTime.ToText(StartOfLast4Week, "yyyy-MM-dd HH:mm:ss"),
				EndofLast4WeekFormatted = StartOfLast28DaysFormatted,
				
				    TableName = FoodTableName,
				
				    Query = "let currentperiod = " & TableName & " 
				| where created_on_ist >= datetime('"& StartOfLast28DaysFormatted &"') 
				| where created_on_ist < datetime('"& EndofCurrentDateFormatted &"') 
				| extend cancelled = iff(order_status == 'cancelled' and order_type != 'SUBSCRIPTION' and canceled_reason == '2', 1.0, 0.0) 
				| extend all_orders = iff(((order_status == 'completed' or order_status == 'cancelled' or order_status == 'processing') and order_type != 'SUBSCRIPTION'), 1.0, 0.0) 
				| summarize rdc = sum(cancelled)/sum(all_orders)*100 by bin(created_on_ist, 1d) 
				| extend period='Daily Trend'
				| project rdc, created_on_ist, period;
				let previousperiod = " & TableName & " 
				| where created_on_ist >= datetime('"& StartOfLast4WeekFormatted &"') 
				| where created_on_ist < datetime('"& EndofLast4WeekFormatted &"')  
				| extend cancelled = iff(order_status == 'cancelled' and order_type != 'SUBSCRIPTION' and canceled_reason == '2', 1.0, 0.0) 
				| extend all_orders = iff(((order_status == 'completed' or order_status == 'cancelled' or order_status == 'processing') and order_type != 'SUBSCRIPTION'), 1.0, 0.0) 
				| extend created_on_ist = datetime_add('hour', 672, created_on_ist)
				| summarize rdc = sum(cancelled)/sum(all_orders)*100 by bin(created_on_ist, 1d) 
				| extend period='4 Weeks Ago'
				| project rdc, created_on_ist, period;
				currentperiod
				| union previousperiod",
				 
				    // Get data from Azure Data Explorer with the dynamic query
				   Source = AzureDataExplorer.Contents(Cluster,DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"created_on_ist", type datetime}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

