table 'Food Orders Count Last 7 Days Line'
	lineageTag: f174ce05-377b-438d-ae2e-e5fcb638c006

	column COUNT_id
		dataType: int64
		formatString: 0.00
		sourceProviderType: bigint
		lineageTag: f7a4ed4a-963e-44b6-a37c-b3e9ce4fdd3d
		summarizeBy: sum
		sourceColumn: COUNT_id

		annotation SummarizationSetBy = Automatic

	column created_on_ist
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 482d899b-003d-4b21-8c48-873b72a64849
		summarizeBy: none
		sourceColumn: created_on_ist

		variation Variation
			isDefault
			relationship: c2b85ee1-9c27-4375-9943-38758f3cd592
			defaultHierarchy: LocalDateTable_46a59ae8-d49c-4d01-a780-5bcb177560cc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column time_period
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: bb41aa76-60a6-4067-9169-4067ebe562d5
		summarizeBy: none
		sourceColumn: time_period

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 9bbce99b-8d50-43cf-87c8-a53f68857c59
		summarizeBy: none
		sourceColumn: Day Name
		sortByColumn: created_on_ist

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Food Orders Count Last 7 Days Line' = m
		mode: import
		queryGroup: 'Food\Food- Last 7 Days\Food- Sales\Food - Orders'
		source = ```
				let
				    // Get current date and time in UTC
				TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				// Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				// Get today's date in IST (removes the time part)
				
				TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				TodayDate = DateTime.Date(TodaysDateTime),
				
				// Get the date 7 days ago in IST
				Last7Days = TodayDate - #duration(7, 0, 0, 0),
				
				// Last 7 days current week to 12:00 AM IST
				StartOfLast7Days = DateTime.FromText(Date.ToText(Last7Days) & " 00:00:00"),
				StartOfLast7DaysFormatted = DateTime.ToText(StartOfLast7Days, "yyyy-MM-dd HH:mm:ss"),
				CurrentDate = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				EndofCurrentDateFormatted = DateTime.ToText(CurrentDate, "yyyy-MM-dd HH:mm:ss"),
				
				// Last 7 days previous week to 12:00 AM IST
				LastWeekStartDateTime = StartOfLast7Days - #duration(7, 0, 0, 0),
				StartOfLastWeek = DateTime.FromText(Date.ToText(DateTime.Date(LastWeekStartDateTime)) & " 00:00:00"),
				StartOfLastWeekFormatted = DateTime.ToText(StartOfLastWeek, "yyyy-MM-dd HH:mm:ss"),
				EndofLastWeekFormatted = StartOfLast7DaysFormatted,
				
				    // Reference the Table Name parameter dynamically
				    TableName = FoodTableName,
				
				    // Format the query with dynamic start and end times
				
				    Query = "let currentweek = " & TableName & " 
				| where created_on_ist >= datetime('" & StartOfLast7DaysFormatted & "')
				| where created_on_ist < datetime('" & EndofCurrentDateFormatted & "')
				| where order_status == 'completed'
				| where order_type != 'SUBSCRIPTION'
				| summarize COUNT_id = count() by bin(created_on_ist, 1d)
				| extend time_period='Daily Trend'
				| project COUNT_id, created_on_ist, time_period;
				let last_week = " & TableName & " 
				| where created_on_ist >= datetime('" & StartOfLastWeekFormatted & "')
				| where created_on_ist < datetime('" & EndofLastWeekFormatted & "')
				| where order_status == 'completed'
				| where order_type != 'SUBSCRIPTION'
				| extend created_on_ist = datetime_add('hour', 168, created_on_ist)
				| summarize COUNT_id = count() by bin(created_on_ist, 1d)
				| extend time_period='1 Week Ago'
				| project COUNT_id, created_on_ist, time_period;
				currentweek
				| union last_week",
				    // Get data from Azure Data Explorer with the dynamic query
				    Source = AzureDataExplorer.Contents(Cluster,DB,Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"created_on_ist", type datetime}}),
				    #"Inserted Day Name" = Table.AddColumn(#"Changed Type", "Day Name", each Date.DayOfWeekName([created_on_ist]), type text),
				    #"Extracted First Characters" = Table.TransformColumns(#"Inserted Day Name", {{"Day Name", each Text.Start(_, 3), type text}})
				in
				    #"Extracted First Characters"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

