table 'IM GMV Last 4 Weeks Line'
	lineageTag: e42a888b-e7e2-4839-ba39-a0ba9b984a51

	column COUNT_id
		dataType: double
		lineageTag: b0c6afe9-737e-40f5-b1af-b355b6c5c397
		summarizeBy: sum
		sourceColumn: COUNT_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column created_at_ist
		dataType: dateTime
		formatString: General Date
		lineageTag: 47b1bf6b-b24f-4798-a8f4-f39ef4a4f5a0
		summarizeBy: none
		sourceColumn: created_at_ist

		variation Variation
			isDefault
			relationship: 02bf183a-4712-456a-9916-e4d4e717bf33
			defaultHierarchy: LocalDateTable_be309416-5c19-4bd8-bbc5-c1c2cd30f2f9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column time_period
		dataType: string
		lineageTag: d0a7e85b-390e-4bce-9da1-0575e51f2256
		summarizeBy: none
		sourceColumn: time_period

		annotation SummarizationSetBy = Automatic

	partition 'IM GMV Last 4 Weeks Line' = m
		mode: import
		queryGroup: 'IM\IM-Last 4 Weeks\IM-Sales\IM-GMV'
		source = ```
				let
				    // Get current date and time in UTC
				    TodayDateTimeZone = DateTimeZone.UtcNow(),
				
				    // Convert UTC time to IST (Indian Standard Time, UTC +5:30)
				    TodaysDateTime = TodayDateTimeZone + #duration(0, 5, 30, 0),
				
				    // Get today's date in IST (removes the time part)
				
				    TodaysTime = Time.ToText(DateTime.Time(TodaysDateTime), "HH:mm:ss"),
				
				    TodayDate = DateTime.Date(TodaysDateTime),
				
				    // Get the date 28 days ago in IST
				    Last28Days = TodayDate - #duration(28, 0, 0, 0),
				
				    // Last 28 days current week to 12:00 AM IST
				    StartOfLast28Days = DateTime.FromText(Date.ToText(Last28Days) & " 00:00:00"),
				    StartOfLast28DaysFormatted = DateTime.ToText(StartOfLast28Days, "yyyy-MM-dd HH:mm:ss"),
				    CurrentDate = DateTime.FromText(Date.ToText(DateTime.Date(TodaysDateTime)) &  " 00:00:00"),
				    EndofCurrentDateFormatted = DateTime.ToText(CurrentDate, "yyyy-MM-dd HH:mm:ss"),
				
				    // Last 28 days previous week to 12:00 AM IST
				    Last4WeekStartDateTime = StartOfLast28Days - #duration(28, 0, 0, 0),
				    StartOfLast4Week = DateTime.FromText(Date.ToText(DateTime.Date(Last4WeekStartDateTime)) & " 00:00:00"),
				    StartOfLast4WeekFormatted = DateTime.ToText(StartOfLast4Week, "yyyy-MM-dd HH:mm:ss"),
				    EndofLast4WeekFormatted = StartOfLast28DaysFormatted,
				    // Reference the Table Name parameter dynamically
				    TableName = IMTableName,
				
				    // Format the query with dynamic start and end times
				     Query = "let current_week = " & TableName & " 
				| where created_at_ist >= datetime('"& StartOfLast28DaysFormatted &"') 
				| where created_at_ist < datetime('"& EndofCurrentDateFormatted &"') 
				| extend counter = case(order_level != 'ORDER_LEVEL_LEAF' or isempty(order_level), 1, 0) 
				| where dp_order_type == 'INSTAMART' and (status == 'DELIVERY_DELIVERED' or status == 'COMPLETED') 
				| summarize COUNT_id = sum(gmv) by bin(created_at_ist, 1d)
				| extend time_period='Daily Trend'
				| project COUNT_id, created_at_ist, time_period;
				let last_week = " & TableName & " 
				| where created_at_ist >= datetime('"& StartOfLast4WeekFormatted &"') 
				| where created_at_ist < datetime('"& EndofLast4WeekFormatted &"') 
				| where dp_order_type == 'INSTAMART' and (status == 'DELIVERY_DELIVERED' or status == 'COMPLETED')
				| extend created_at_ist = datetime_add('hour', 672, created_at_ist)
				| summarize COUNT_id = sum(gmv) by bin(created_at_ist, 1d)
				| extend time_period='4 Weeks Ago'
				| project COUNT_id, created_at_ist, time_period;
				current_week
				| union last_week",
				    // Get data from Azure Data Explorer with the dynamic query
				    Source = AzureDataExplorer.Contents(Cluster,DB, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"created_at_ist", type datetime}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

